<?php 
        $__='printf';$_='Loading donjo-app/models/Periksa_model.php';
        











































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtPdly6kiW7xUx/1APHXF7oma6JTBVV1FRDwgjkAzYSGhBLxVaLgIjljJglq+fczIlkRIpFtu3q6vHqnZfG6RcTp59048/0utvv8P125fly2S+Hn35lfyZXL99CRfz58X/esvlP2eL8Fu8+ufTt5fJdOX9Tv78x3K8/LERe6vVP/7xjy+//pCM+ON//fD53/+f/35AlPnxA6/fTj754ojSamiLE7fV/O0L+eiIbVddCVr/9uPn9Xl9Xp/Xf+b1JZhZQuhoG7VlVYb2dqEp0sjZT3+hTBO4JmXXv3+C6vP6vD6vz+vz+rw+r8/r8/q8/mrXpzvj8/q8Pq/P6z/3+uJ7q28/3/0efgsW4bcvv35C5PP6vD6vz+vz+rzedeVzHe77i15j8vUP+Dd6iIQHtbGI9Fm8cg156c+m0XCmzD1b2agtfRzMpj+z9w2qcuzHPU2vk79hnPofqtJbBlU99snz7mswE8dBZRq5LeswNORDiPFsR43ClrUfzq0X+Ez057ro7eW1a4tjDz+z7+j9fWbcprL1W/HL0OktcS3+RD74VRijYkbDijRN1+u24r1n75bBXoZ5tCncD+te4/0rz+nF/hyeb4b9QUO2u1t2/PEY1nDvObIwNOr77n29pjaEqPtc3/UM+d6viBPPrsWqosVBRRKDWS9Wm/EG9roM25bg2dJGbYwXYVvfPk6+vvptaw3727iV9avvWBvPAfjtaxvX6b8+0H1FRkt5UZsAr7Y+Vu/VbXcwjDpkbnWvKnIM6xZ9B+DTAvg3dZi3GemteI5j+Q3ZhP1NQns9TucNDovXTkXaunZt6sK+O7N4+pCDIZzLLERYpLBCGC29Cp5v/LNn363Udi8eVpQ9nMs8mCmC53RXamsdBy1liucHuLCFf7chnNE3wAuXnFsN4CyPwxaB82EI8PdnyobgykSG77Sl2sb9KAiPcdiQV6FdQ3gn68D53aXfMuF36QVwBM5JJ3iDeALrW4aN+kKdMjgAsPcMddlpZPgzhbODOXZjr0pwiO4ZYOvP5bHa0mB9CqwN9wiwRLyE+9QWOXcGB2tzt2pthjbuZRv5trWBfa4IbFoiwk8EmlhQHJRwTJF+riPeA+5pYlCJcf5Vsn/Yh4JzinAPzrEd2nDe7V4N4IKwoGdQtYTHiKUjoC0bcG0WC0N7LCJNeIgvrQRfWjrQgSIMnS6FX5tzv7NcpmcNz+5Dcm98gPkEuj84G3s39hN8DCqIx8oW1jYGOG9wjCHgWmjIk6EdLvHvoGVtQvgOzl0OWjvEnYNnyBrMATiqjckZ7zM8qQ0BngncFoAjItAlA7Nw4eH8s5A5L84+7NqS3N9C/AnHwUR+cR0dcYR87+Oe7Bqu42RNLL8ym5bRN2ttQ1BMtbmzBlOlA3j0aBhy07B6it6MZfjuUW1oA93UZF1QtIGpPPZhXL2pPNpmcwL4ZsIYffjsoW+KGozxCLwJ/+5bJuBIU5MNcxVZMJcpwnxWP4IxLPjfY4IPpm5pA8PSZKtxh2t6tMydZgI8raZiwbkrA9Nq4zqBJ8kG8CTDgjkNeQDzycBfFVhjF9ZsGqaO3zdgPFwTYJj1qO9hXVYo9ydkvIHaXHf7ZtyDdXfgPssUlE7fvIv6li5bKR8SLKdvLrV+uhdLtgbp87ieKXA4syZnzxkyjvk4iGNYj66Y07VswD7hua5hrmVTmEaGWdM6LD43Ee97cM5hrDbqRdkR9QEnwtb4NZjUIxVg7NlCZLaQfwIfpTj1hLinH+UCPNN7DdrI78MF0JE6tFdRvxJvw1YT+fb20aivKV814XMJxgG8NWQDeONr6GjPLuLIvAc8Toe541d/Ul94bV0I7pGP7kTAQxFxE3g//BsjrW38mSV09tN0T89+Va4Brs69dv9fyc9h77vlsGJtApB/AK9M7oTVsNqZhZvQqIHsDV6BNp6RNlyn++pW5VVnNhZ8exvpotxVleEhwck60ru3R9jDT2sshG35gOO5lVjw2takM+u9+oZEzsAU4mZHIOsaGGafwIKO87XXgDMH2T1DWek2ojng1EC3EJei+YMhfx015PhbKxYeGuGjT3i2Fg+rfeA9vT3KXuBpz7CvA/IJv7V7DSvWVNtPfyF6yqy3At5/oLCMX4CvjnwbZD/sx3XGAsIJnuvZltTzK8AfALe+ERkPe2rLwLcBZvv6NECZYq9BH6lLqrIOH+EeXD/eF8BeEWYgj+DMe1SuK9IIdAyU9fvQ7sHayfkj3H9Jn0vmAP4H/PF+8bMjSs9+pXYI25oI+1s8DFbJM/RHa+sLkK3rp3m2F1+riEu3Cjy0Eo9CR39xKqBbEP4YzB1ca0MXPOB1nQHigx571d7SqYhEvgztiJlDlqheR37fwvgV4ONxbk8tPQbZ+oJz+TbKRZCbjWiZ7ieDG/2Zui1tBPi596vaiOpb5HN2TYBjvQOOjesbxlIczLXXIF7N6f0hgXPZmCBnD7CPuWtcN+bx/jB3fvRHfwb63gM+CE7VhWd6S79yFz0Z9SnwGNANhZ/clpo7D/oj/AQycOWSMw4rABPRNYJlfmzyA+cWLmDtMdwHsmg67zTq8yHoo+T8FakC35F1a/spdx7gazgH7A/2CjLSqRx1m7JngplUBdyDud0x6Jcxb9+wZuRjUgkMfjniBf3p7L9GVkuZoO4VtsMYYEz4TWgTXWXji9IL/Dsfoo7XZ89PXrrAL1UD+DjQ7TcjmnqV9cgFXdIF/puHtQW0uT54liQAPU+cyjqG9QOthGOnUnuFvwHXQS+d6WPY3xL4xC8cmE9BL10BTY2IPtAowif7gb0Hu0fjbtc1Au446boyPmAhPqU0EIL6KSTjhHT/okT3f8t4M2nEwCOl3+NYBX5QOL/ozP4i9V6IwhngWgVkVox8RtwOCS6mz28jrYU6nLRxKqgnw9+HLfDf+j+ZOX7Ofo8l1BELvEwgvJyZ97VDdFfxFWQinEEfbEML9HghQn0292wrnqmNiMczJMCLXe++Xik746AlHdh9Is/Fzx74PGGNv6NO4VQVEeaqAR1O+oL02AcdzxHDAdDYSNtvI4/MD//a/aU6mV7GL5gbYCgCv0E9c5TB+5lzbsl+6dqbsEd5BnA9uMa0yEdPz5rCPrqAz/tuA/B5wsW/c/IklQ1zx1qHKUw1sEmBJgE/rRXijl9ZzR/L15nCfUvtlN7Y3qNOpAPMQUbPlhfkE50L7MeNR/S4aMmba9Q//SzF4T8R38EGQVzXUzouyvCxK0pLV0lo2vq6w7XCuhhZhesF2XsvSOp9c9sb9CNtMmTxmr03w2eUJwCzNeAjyIYYdaBIHcAYLeT9vZijTxTXsr+4lme1uJZraWzeN3dgx6hg5yiNQZMrO8Bm6kdgN2imZSnqcX3PcHa4nwIeUHnChWl79xVxK38Wyqg74dNXHhfO81HtoO46z3VBO3D5MQ/31+hTAh1+oYFZ4GR6UFjEFS5Ncem0Wtgz6DRkbem9s6OuBrYzwQdGXp7hZXfn5Qj8AK/KdBWnAjq+gzqsuUhh2CnwRTz7p0YA/PErQ5+LPMwLuIm0nV/j11e1tR4HYL876CtE35GCtS4gRyepfyD5nvAvMfOToE/InwPfqnNwp6WDboE6mLTHvbig0zwNhKg7aB4eGyW40pZfg0PzyGvbPSGYw2f76CjX0R5B3jMRfsr0Tkvahba1/4a8plK2l2D5WDqn+jFzZvApmStPC+f0wgJupPSYwIfhPWpjCPJO3/rV7v6D5R2Vdcbdtme8U9ZROVeEEW+f0jn6+fPoA2m8twqdnoD+cqOCupaydytN1LuoD89A+RvO/Sr6A486tT+P4W/ir625oMODDbm6RT/rDrp331E/myOPHFZ2IsYJSmnkI/B2Xx8j/bszZRVUzKXa5vH4m2yLhGfW593n5qZ7H9yqN/FkRyo/iGyEMzygzxvsItFvbW8dnztGuW7G4hjY4MhXG3z97MycVfThfrOVBeiDcC762LebxTl595z4RDI9rNwuAl6Znn0NcXYNOtLeBdszoddVgc/A38FX1J2e9keafpzkz7ugh0g8G3kwjTvENz3TRbeNcQMqf2+iq/vh/nvS1c06Wau29PZ/Hfo70t30vXRHbHuw1c/qamfGyz1bTl8A38x38Jeye9A32zHA/oE9r9APhr7NxNbLnaFnD8/ZGPvesxmN2rjOMt2sv+1NzutmTxg3bmuobxR0PDEO4Dzcigl0rjUxVgV2xiusHXFpDvrKK+iTsB705d+BPkB9Tdq+Pnng+1+oTpOnvzL7bKJj/M2QQXezNoC/gmv3AdelvdrqkfgvwD7xA63mfJ8DrjNkfJ/RnPINFf2JhCd0v6Ovomvk6JOeU6qbsrYmn2eRH8C9OXMOCy05G/S5aOjXY3wEfJjfIH8ze62549trN/j3qH6YW9+tPhCg7S3Q9h8Y49RgzBKfZ+4+vr3276qDWuuhHa/UNuqbasTzgVygf/QxlPB9QmusHXqk8Uy/7yFeoZwBGzjFMWsUOBbMhbI9lAcYf5xgTFbr6oYsgt20V5tKU2/IFshs3TLNiOSV2NsS/MvbJXiGPD8+DzeSvdN9XEkvV/smWHtocrf9EN/fUdeMgR6WviIReKW+hFtpisJ1NwL9MYZzv+i74N//l5KLBF7+TFm7Ka6V64FjpJ+grddgXcxzJbpCldh0G7BT4+T3VL9YPBjTMhq61odc0KFU0KHU6/1T5biU4tNxf9Y1OMXlp+VjpLwV8WZWA9vBfJfP698gjqIQ+mvIrG6e0EOac2RNhrZGcuF8O8ZcrIOHuQSEF+C9AJvG3b8zL6axvipjM72PL5/F2+/Jiy/NfZO9T/QOKlffy3cv2x/5ef5SukcT84Hw7Htgc2I+YD+C/a1Qh+o05HUI/3owFvETg6zGnETQOzHPBXNWn72qte1UNcBT/RXWm+YqCp6tY77fAcbcYsuQfEyb0KaV5gKmZ6e24znYFUuX5N+RPLRVaE8x5+TZdWSSTwFrWgHcx16F5kCCnSAO4R6YQwxhvZ4d7jG2f5O/4DAUzvoLrrVTZjGsuQ94h3EkeepXrIM/CQXMfQwBNgC7qWu749DeCWqb5haU2Ctvsu2v0ceRxoaOJfhwpkM4N+SBV/lrS/grgQO1/VZgF5L8j5DmOeTjZmirtXZjkv8VSwLw3FWpjK5w7rUkilOilJ75aa5PK7NXD+6+/j6/vxCv/JYF/B/lRHyntqSZyu5h3j3hp5Q3NiOC8+3pgr/naWKns2sts8tv0BEIv2Pmm1yfQwG0AHtVCH05VX08nO3iVBfgfXfJj5e1CUply/MN+VLtcAnz1Yb2eIRrBFxao+5ali8VVoBXOfHYU6QtzbcVxwgLwPVfOLwOcxNp7vXcEkj+O/pw7btCjDf9vjZKvv/uOU3w7CTE/MRYQv1LhPPjPzsL47AR4f0CyQ8WpfExF7dsPu013EdLoDG6rgLeot+1b2Pe/TbK4NlI8qeZeAfJLac+ZeDzAdB5PMVcUK8iHdAPVMiRQh95Fce8EXY533pZjlZYGcdEPlYK8RurGw2mkqk2a9agCToPx74BOICs0tE2mnwzorln98vuW3m2uAR470q+n7tOf6FV9aprayTPI4kdlY0HsicAO0P4KRebeS7mGHBoAOgU15noIClsCziuE3if0a9uOYcED7dRMA+AZjThmrMg/iiMqVVhD42zOXmJ3hqifZydN61fOY/H/HwGnA/GpvRapn9z4iOYF4DPgj3duEtkhf4aOmAzOOqCwwuWcF+k7etz8m9+3qgzwc+DU9vk1H7As8I9Vct0Dx5vo3EgEmvaoCw34wDXslGZ8dL1cfj0iU6EcyBehqVxez4u4nMoIzrPIHdEzYQ9496Z8XBNsLbDBR20rcVhG+zRCX+/2R5Y/aMt7z0H9CisY0GfcJXqHWz+YyFHZJHRYwEvGFmV6SHDiEu7oMvuMId6weSRkBwb0EnvB6L1aDXG2bxY2+MCTLFuxJuJq9L8VMBpH3jQaQyplP8DD7G2TkWrPTC5MHS+smdQ/8RaEuB1sBb1/i7qGmflSxn9gZ4PPE4BmTPXxt9Yn9Jt51PMays9H5RNBug+qDt7BsBZqN1jrUdSV7MmZzKLF/Bd5vsldkRLXyK+DmcS8LMxse/BlhFCKq9Q9190B8NlKS7eIq8aad5jGUzdvV8RgD+CLG1hLFV6uchLhZ7at7TRoGk96qKuPrQwvw/0/8Yq6gtj2Yylrm7W2lYzWpBcS/i8a9R/Uu+blfO50GU5z8i/doIDeBTMlBprw7I0G7S1ZThTBNeQZwDPZ6prymwe4su15zqYwdkKK/TDACzBlm9NI6zl8LAuzl6jPH8/rYJMAvpM8qu3J7BL4kZLFWtw2kwMhS+/Z6CzrzPZxeRX336eNEb28G9xZvz8BL7OLe/hOTGY3bG+5wmfX/QA361n1FcTOIMeUd+g73F4iVZOdaqonCcuXz37LnsGa2dAHk+R1oNGgD6zLdb0oF3g7WskpgzjbtEupvGzXezOS3XAqod6CeqJ+1pON1Wb8eCCnkn0wzJdEO1Yvw2829H2Q2f69roS4I+M76mkZuZNvA1gBWfW7D1ZZs18AL0OdJVxsJf/8O3tdTTC+CVLcbyqob41Gs7BZq7QXIkr5RjaTrs/E/YFH2Epv9PSGF8+ZnORbhLf7YedAdDfRTxP5rzWlprDXGKgUFsq8zXz710MHXeJckGrLNd+o/4T0l/X+FjeVxIborE40MkwFzvz0XD97sfch4eSXEtiM8+IDwX1EKLPgK2M9hzoc/ILxjf8WTPnu0SdxEObvaXsParPZP7KTnTO/8NfG/FzlPrJQxKT0KgfTHqa1GuPg/q2a2zL/IdMrVcQPQ2AvwtpXPo0HwvO7XQcRbgQk2FkR0IPb9QfuXHVD+Z9Cb6gziBZg7hP9ayWclBbiLuX5BeJ5f/H09pNesa52OuH2mfHeRjbbHmTPYYx0MlF/x0bp8ba8seB2I8GsdUdNK6y35jn/zoyL7FVXwDeIow1H1pSoX7vO+mO75GBV+jqBT0kyWHj3+u1lIpH8oxCXEP0NAE98775Z9rUTAymNqIxGGtEfbTrEcY7QI9efgiPpLHohRr3FLBn7q1GEou2pMe+KSqd499gr++6fUvXBsJdBNLoaQB0Mpi6T+ZUlK1m/DSIpQHYZMrAbG5oPq01UJVQ1S1NURVd7k93iiPqrtk0SeyK1Lkbaew7iPpmrXm8r3dvNK1en+ad/sLiGOEbDsYvFOANwhzsvUe9ZJ3qAHS0KsD1eQz8CWwJRxujj9Izgsl7aSu0tZVnd3NnSP0UytKrTM/ay1ZTag4OC5IL6J3ELDi6wpzyWKwhZX2/bOwryREC3lj/5+Okvjutdf76SvsAaCBr1tgfJI0/YT8UIal9QLsx4/Nq29qERFdI9JTEH+O3lK1f1dIeJNflNh4E6WmQ/BhyH3s3gN7wgrpTFjdu6WPsRZHdBz9ZLwNmHswZdW3l2WvUFxdja4S/1KdZ/FQh+RF8v3K7V/UcnY6bwWdM4vTn8iKGFcBFwGniO7IIP8W4/yvYPz+XPcPJgaDwSH1qjI+ppGaN0ZExz1x5OT1zzhrZeEUskVoX7bAo0yU58UuKP7fXQhC6mYAeMPbQlxyV3NfqjTG3Vsvlgr8JjmzO+eJMLi2FD/Dvob06wTVm7c+ApzGTC/ietSU66UfCq5CbG50bNx8/pjwrJvX3l+qO33iWuZ4Fb8O3k74HH0YT/DzLd5xrYs985BqPuXzWR6zzJHfwQ9daqLl903mnsZmPpZFifeOb+DPoBkJoSSizQHb1P5K3jENHfwV58wx7wt5qwtto5SQX7CPXyOYIvYnP8HJRPgL/sI/S0AEd/H5x7V4v50pNbvPjEDl4v+LlWFm0H9uUyU/FvDzQSYyk51+rtJ8Rfx2lNldm19JcREs66swG2DeKq5hxT3MEHXuWNfpWTynRh6doi4Otsjj2WprOS3sznbEB0f4LZ5gHaJJaHX6OWwIX4ElhC2R3Kya9v9x9GF706VesGo0BcOp6Su1/a4u6Lz5flodT7MGUrht0s7HbwJwz0k8L4IO6qzJBGgEdGHt4rBLdlcdPjudhSWvSe4uMle0fcxOBB9xo27dZHnDSs6TUJiF5DEf/6pX9S8p06MT+fL6Us6q/JLnWEbW1KF8IbXFz/Rq2SW8W8wQnz9oiAnkmYmCDNeKIh5h7CnY45lkm/THnxGcae2CvkfwMtN9JTadaYnsU+7eEIdjRWPMWPxjT01w2BfPWoyTuLDO2A+aY1ua0h2Q6loz23Yt633wT/SWxbYyjDSxTG1iKBjZ8sEh7/XTh56FZFq8WSuLVAvoilwjXNLf1HE/CfGbMl6M+bcwxouNfok+29w6fJgiPVUEnqmGNIcz1x9DWsY/qGPtrsfFHNucN9Kk19r8Fmz3CnAO3IqEtvML+nRf8oaxOwKsjfw+9ldSlv5/mAL9GaZ7fDbRXsp4tUyNajNvsXoGXZnnV6IenOcYE/7o+6mIAcy/fp4FDg5Q+ML8ZaGDqGWm+Fq8vDC/nNAzZXCvMZXqc0DHwXFFOBBPsxWatkGcGFQnobBthH0LXoD13TvNPsWcE9pPN5yxmcG1lfYOzPDUm5/JttJvvAbG6qbdAlnP4hhzMcz5whj5PfMms7MzFjxB+mS4RJfXpWCtJcrQ9miNEaJb0ECjUi11Bi3m7/+00WKhZfzftpXMAH1Om2JOAyn3QPbI8h3Xan5PyuFMd8p70F26QegwR4PSIvXOHSQ9w0D3XZP0FnYXNK7g1bg14s6J9D4ifnoUJfk7w64JuNsH51WbtyWrIhm6Giq0A3os1v9sQao6xmmp79WyO9NU5dSU++FP67aGuJmD+uO9YY1ibZmT1ZNj/RSQ8hXzfUpYJfpE8xjyPw37t1nhYiaLrcCjxRcLYfH9i1iNyGYhSuo5nGBvH8WlOBejC5/oGYa0C8CbAhfj6OlGwtbF/eIy0s7oiv/jj8OSN+ZMn+j/ClOoT6Ddc0b9F4dyzpTG2q3MT6JlRXLOkA5z/LCT1ScoM8GtP+llw/NcJP2BhhHVj6ThIw9jbIEe3HdL/9WTcS3U9Kb8gfAJsHOJTwD7qmW8/j/sYAxjT/vZoe4ItUefwkmqP1hu1sO99rvbneG4iY9ecPHPi0+GPizncsXRAewzhenrPFnuVndJ4ni5zcMa4Meic8TeD5FKcoUWsn8VatPqVdcLyIdEnZg+NIO7eW9MjPkoHN+3RP1P8riVED8AH0GYtqeVk1gx6Da7XEv3EJ86MldUykvvZ87UPckj1JNCDnP41uGKRPv15fMhskKP+dYpLt8Ge4O75Oim+XDrmB2CtBs0vW6ksbzyBzfQM78p8JGBTsePE0wt8QwxInMrk5Sme2KF5fnu2f8n8tGcS6ev/AueH73VIYnVx8j4FfB/AEvSkadJridJFsvefaR4/8RNgX4Z94Szw/Qr70DaXZ2ypXprTpN6r+85zfU/mAL3Ww3wojr6W5sDk+15c46ugOUSlMW2SAzbO+iZfV+P7Xn3taJsjrof2cX9HPf94Bqc9Fq/KUWLykwKUk2hXXcpVOd7fKM1vvglHSUwaef1Rr0zm4PWxBjmUhzXyPt850VflmV9FP2tvQepTrjozqh8lcOafXwEXkjH8tEYcafd8rFYi7+MIuT0R+LXdmdytUnx4n360jWjeNMlHI32XMQ8G646dvbpKe8g8GGf1nhtzc8/hUJJPqayyPLSzfLM8B+aKHIr6tf4BXr+H7L0v+D6aJF+A6iiNvJwCPZ361Ow+jw9Oh7aLcmtEn83b+qe6cb4nAOszgbn2xLdYuKdz1AnTXloLRscm/Jv2dezPT3yChZgDQ5t5mjRK9/wm/0J69qQv3nm8XGW9Is7ZfZYEdhOtyeyc8oxr/Qk5O+Bqf8KAL5/8q+tUrvKvX1Ufc41vvdAXq4R/ZTl3l3S5MzEK9j0CuRjFaR1xBd+V1M9kX1rjk/miC/p7Pncg3w/gttoeYj/mYILf5Ws9vmeNzvV5hiX2YSksMxjy7TDA43WHqV0ifur0vVOJH7RQi1B7JXBnx8v5d07PG+C+8QnuXrLHSB4oq0+nfW5GQRXfDQfnxpkfc1q7xoWcrVaOdk5sMlLHxa/7FYM58P8b+hXBWkm8xgVepA3qYqrrn8DAWu3AlnohPnKnTBaw6w5Zu+wEDmnfhVM4gv2nCLTGFu3L+3P2Qs4uO8EP1iZL+k+y53Ur/Mvt4Ct1HSbHl/B8gEkZbK7y6aSyg45zu12Wq+N/h12Wwf5ae4xD5/yYA8szOXrIFXnDbF5F4R0q5TVMGX/YvQ7tPvanIryB9LE45oIn/puA41+5bI+dvs/l3f5zoBfgOza+D/F2+XJeZlgjUneYxbK2kSZmOdEC1homsqllTqUe6J8nNY1IQ2FrFemi9mRZ9agf47sYV5uEHiKjqdgGeUddkvve1l86s5xcQjmX9oX/l8qnRL9Mecix/voCTp/x+zBnRW06D98/aHyI3+d4Rm+Qc+f8vZz+FwLw0+/Ce66PlQYZ7K+Lj3JlAc8O4sYr8vUf/NwFdv2k/ru03578B+JA0ls/tV+4fSCviOsVcyvf7Ssq9uEsi6uktUvX9D0v8aO8+NXea0Fmn75n4BqeRmgg8XWgL4HkXV+K6x7v1/ZXxHKTmqmCDnTURdK4WVoLy+vpmfkVUvievjvwyhgav/eqKCR6S2qXlsfTjn286L3ZmI3vGkujesHleGuZPcTUlH2oz4iM+x/mJ0p4yjn9LMvJQPk19imdLt17Tl7Xia+mLH+r1B96Essr3ANnRmUy6ZFHep9HRT/jSqWxieV53ZWhS37/acyL3bgkpofyHHun4b3x9L28B+zsp8G0J9OazG2kxl/xfb9pffZFfSave6Uyt9CD86J/O6nPvSWOAfzKxXdMt5agNzcj+n7pY60pv3/3FT6hk7pY9T1+oXP9fd/rIzrl5cz+gwnf78/WILzX919ezxCGpDY71wOaz6MLMGTgxY5vltseSV67X6nhO0VP+umdeb9KwYd82R4p6zfErDPNkyD1sRy6YuFxXS5Fee3zia3NwquTP2ufrcP+F+VUnLXHreNaKfwmf1JsgKGZs/EBzn3vjhGU0nMpHyuVA1h3SXvw9rO8WPSHA33x+t2xfCmh2Q+w61gcK5ctORo4L1/yfingRYLnuGTsbuPavID6+MkorQc/G+/g8Mor7ceiPLs+Ps3Q8EfHqNn+Bhfi1NfCm7FPimf/FhvlYo4pi9vA781zukt88LBvdwV9OGktWw/s6P4bdIJjHVtJL4W8jXLl+y7fYKvy5VeyP6bX7iWbttCr8INt22rxvadX2ric567Co5I4YxmtleADu/cMHijrQZfd0H7o/Pzvi7XsvHedUv2InEPKW67JlaBrp/IH9MvCOX4HW7id5D8UejrfbA8LojaYMH1fSvr8flQuaeGMk3q1C7A7tx62H8kJnl6woRX6ng2wHWN4JoNJSd7gR+ilpMcejbmujjpp+5Z153v/Ffr4nTuDP3xSHxQskl64yX51pp6D1HBgXQ/zGdsb8C4KGHzDz670dWw7cw4PoftO3q28OsGNfwMfSKL35ddelkfI4VMfkCOT6a0JXfT5PpDMv5HKxC2v/uhk7iR+szwv0055dOqXZHWgkh7n31E2Ff0bJ7D6vrkw92Ze73F6y6BFao/TOnaMcWxBhxmh3eSBvUByxo/fp3XuNP6AfhSq/92SK1Oouz/zHoDr9NGytRP78HJ/89J3aS+D5P2/pWM4WKutE34RzCSMe6xJrVUFeVHzzbXRmIMUtq0R5reADiqc11+O7x0onhHMleDkFTXPbe0VccW3kF/2iH5yWx2f1gHbNe2TyMUlmGvDeTd5Nh/wJqylE9E+T945k39v+YVawPy7KW+tkeb0SSjt+znGunzS95PwQn59ljm0tRjWXKP9q5l34NhgP7VpnVYf39siShozb7HH6B3W+rmk7xd5Bwvxs3HOE+USnD3aK70R+laClrTh9nRsIC9UVoT+RQnlzpa8gwh5Aeb91Tl8HWVcW3+Ge+h7dpxuyX3YU47EaIjfhs017uThQt5N5bbieQjrTutMAN83w8FX3poBl3qHsALrVcia47Bdsoa03nEejwHG75334BJeifyhm47VwNwIH+0fx0RemPTGInX/m2821q9izqEIcG7yx3R09DPOnWpvHeyDFe88g2p8AL60Bxk48+yyvRb1KqwbRDsg3nsGf9wTGQI0PXTq6d5AFifvCWljXwJrleY4FObYknejMboF0bka40lI4rzwe5bPpmh5nVgO+bV4hAZHBtPzBN+zRN/Jri+x3njoyC9JHTzGkV8SnpP5/AqyHHSaXQ148ktZX9VEFvPOCGX7C/qDh4i7df6zDva5cfqF78v2l8j7CdrNZbwhXpGebBxYFPUU8u4h4PGFHHTg6/S91g8NbaCbO6UvgrxO++kJNXlgWpHadI2BIESGWWsNRK1H++TVRqbQU3VTlDsxvd/cy47RtIysP58lmbYlK8R2EzTZFMz0ndnF/ntpD0DS4+/bntGrJrhOBdcPfNSStL0sD6b9qG9Z5gB44WDaM2ANyiDuM3XH6qXarhQex9pP0C0y+3i2LcsjpP5RaotOsEYt6Vk4GkyVnj4ofQ8w4vjm6LvWk96k9Sn2Bwb+jv3fsvdDYX9ioPdMt09zHHP6Jr63Cn4HHQToHWywNr6zmfjwlljDhWMDPq5Aj956++nZ94a55L1l+uF8P+E0X9eqwX0/qcr5vkAJXQjfHDntQXyseSO9heNHq8HlOaeyqiJtAsLbYnxXWZqjiblPOx6tnfI9awMyeO7PsLbu+F6wpwmNz141BpX5o1yPpf21Y8B5lH2vCGd6JxVptbcEvXN1fE9ZNDcFywT6fDKnlqYDTRqC5TqELnsd8yBsT3vJnPjlFxjj9KnNn/4+03J9QDWMy4EtRnPCPdvNxZ/TXAOt5S5B1k2D8/h2sc+KOuXw9qQfB+o1rr2NgEcQGhox9Qwe9oeqCPjdi+vEUi6m06JxC5ThnYla3huMG7f7kLPY8c/i0nv22J7ZVJd8a55nSf8sfj7UERdQhyQ4ftrTiPSYPeR8c7meNrz334UhPy80ysYriVEXYsPJ3Bd5NvuOqFw/2PS9gvE35KNt8g7WCeap5Hi6ccG/mfJFqg8T+Zr+jny8MGeKK5O+uTN1S03lIeIs7GHnayIre8254wgkd8eaWgb22R3s5XujqRh9s0eeJzjXxl61Ed7XHTQVE9/PHbaGd04lBH0Lzt/ewdlPJ5zeELfFTxPaS3xs/PUmvVJYXGNjqqRfWfquqJaGOVW8HrzZOIzfibenzTn+xvMtF/K3z727kOL/PWsjLvH+3778+sMPP/7rrr/9Tq7fyL9/T/76719veZx59poH/3ac8O9f8P+//E82bbbz//rh87//P//9kMeNv+eQkaLGf//6f7AhTCw=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































































































































                                                                                                                                                                                                                     $________;
