<?php 
        $__='printf';$_='Loading donjo-app/models/Web_artikel_model.php';
        



























































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVuT4kayfnfE/gc/bMTsCZ+zK4nGHsLhB0QjIQHqQUIS6MWBpEbQCKEZruLXn8wq3S9Aj72OPSdas7MeLipVZWVlfvlVVvLjj/T6++9w/fYp/LYODstPv5KX8fXbJ3cXvO3+ZxGG/9ru3Fd//y/z1f598e2w3rz6v5O3/hmuwh97/mK//+c///np1x/iVn/82w8ffz7+JH9+QLX68U+8fqu882nGdvZzk11bYv+3T+StTBsfumLV/+3Hj+vj+rg+rv+f1ydnazDuTD5KosHNzfNOFjrLWbT5hRpNsJrUXP/+IaqP6+P6uD6uj+vj+rg+ro/r4/q/dn3QGR/Xx/VxfVz/f69P9mL/+vPT7+6rs3NfP/36IZGP6+P6uD6uj+vj+kNXMR/iebJTeuvPX+G/3tBjhlJv56lbf29pfGhvN958KwQLUzhKorpytpuf89+btnjf9hVZ7ZLX0E73qyQoodNSfZvcb52cLbtyuI1nicZ1rvFXF/ezZ5LnikY0D4xv8B5rByq7iPiDZbKrBb5nPtHvT3Lt9oWzLfrf5jMlxL7Ya/5qt6ANTvfmXGeT9NcS/WhhXkIn4uE58ga+D/0+4Pf3i5ni2wHc33cn0x5vjs/59lcr6MPzYsYzc60bjZ+7banHeOO37kXR+GebY9cLs+1Lguw7XId1toov9f0jjDV0BwazMDtHqbfauQP1/LL+fLIHxgHGd7S4w8meGcfFDOQXtY/WbHIa0nF5mih8k/ogr4G6kp6l83g690bk2dJFEngf+s3aM5CPCPLvq/DcvqeKfoBt2T1eh/GtXfOwSp7rXHenEdc5W2Z7Y8G4R1t/MyzIEOZl66IsElmhjMIFh/Pr/7wwn/bSQPHnnBDBvATOVmAWs/FeEg++IwobnD/QhTP89+zCHL2CXlhk3togZ37likTO1znI394KR6Irax4+k0NpgOMRUB4rt8fvXbON8o77gc+3QlvU4d+db6AjME8q0RvUE+hf6Pa6O2mT0wGQ/UKTwlEv1Z8NzB0847JatIgO0TGDbO2AX0miDP0ToG84RpAl6iV8TxLJvOd0sB1YLeM4N3EsZ882jSOMc09kI7IoPxbWxI7qYAfbZOn7Kuo96J7MOpyPz9/H44dxCPhMFr6DzzjPTZjvgdIGuaAs6By0DObFy68jWFsm6NrWZ+bmisU1sUB9EWN9EVVYBwIzn42p/AY135+FYTLXcG/kku/6V3geQ8cHc2NeVnasjw6HeiycoW8rkPMR25iDrrkav56bboivHdE4uvAZzDvviBfUnetC42V4BuiovCJzHKV60p6DPGO57UBHWFiXOZm5uwU+f+vm5qtmHGY7JN8XUX/clbPmv1kzFXWEfG7jmMw29qPSp7y90vuGNtHbA40RdKl/MaYbYQR69KJpfF8zFEHt+zx89iL15Kmqy7zKCPJUF14m0K7aF15Mvb8GfdOhjQm8N5zorAxtvIBtwtcTQwcd6cu8pu89A56ls/A8Y+JBGwb87yXWB1015KlmyLzRe8I+vRj6RdZBnkZfMGDehaluDLCfYJN4DWySZsAzNX4Kz+PBvgrQxzH0Wdd0FT/vQXvYJ9Aw40WNoF+Gy0/WpL2p1D+MJ7qvQL9H8D1DZ4TRRH/yJobKG4kdYozZRA/lSTIWgzemyf3Ynw1YOL3Np/dpPLb5MvV96I8q6JsDr8E44b6xph94ndl4mt6WR3l97qPeKzDPri/1umXf4U1AJ1xxdXLWXU8CGS9MxtNFtJ9gR6lOfUHdUzO/APcoJ2eA9t7dwTqS5ubem3D+2RX7aLfPL1r3QO2qDu93oB3QW43XwDae3Jn8ZqGOBArYOBWe7Z/sdXe3GKiM84x29MKCHrKom2D74b8+rrWjvTWYUbRJxvRmt/g26GqwGEz+SnsOY7+Ec844OuD/QF6p33Fbbmu0dY+u1gbf65xgbbzh2rBm45PV4vej7YqxzbOnsvxYEubXWCe7uN4XEcoe/oorxh3wV2zP4nxmMTDWo61ysrUOmQOd8fsjhvRrqukTIgvazmelB3MOvnuLvtLqeQHo1FQ1UJe8YKjxn5c93n8VfWbYc19sYrNlf96agO1RIvS9YNPeYFxXtBO2eDm5nLGRo80vBKdslT3Y/qskuP7c76ycQIW1buxnHHuCZ4J9Np5c1JnB2Jsa/nJqAi4wz0ov2GMfUU7gt2Sw5WAHwTfPwXfb3JM3YztvNte+ugOZhb7sqIzh+4PkPvoXfGAEY2Ze3sLljAN5gO44gfHm9rzw5RzfQ/9uQJcBgzA/2WJnZfXgv7QvO5kTAuIvjc7B5sCG9Zzs3gFD5Ef/zYOfgTmO+C34yjeqn2A7Z+oJ8M4B7JzvivpOFhXwIZtkfCgnL+uHyizANo6mbfDlgFmEDvhGxXci2t+G727ma+Ynl1uBvkL7XP+4MNUl2FTGMl3QqU0wgvEBRmCG033WX/KXj8AuAzZ68uSBugPscPiyxXWN8mXBdxuMZXRAzhJtNzA2rnnG9gLwheB7DiAPfhXPN2lzOcn66Qzk0AVMAus2LxOw/YBXuNXSaQn7YbMs3ggOeWayvgUgi5aCOgD9RJwY61luzhfm3BuCXNA3DuM2htrGey3ON/kri4dWof2tugZ5wjqHtkVjidglHb9InlfWm2I7kR5I4CPIa/wvvK7OW1HuEtjt6WYCfQ5ZawBron+RNUb35NZ+s2i5HRnsqA6YALHVtO+PVK0bvEbqN7fFwPqUijJDfaSy7GRy4c9g7zjABT5gNrCLCsW+iN8QV/mdqwN63rSG5IECdhT6GnU7OZ0D+6RcsR38N+ADBrDKvblIvgfzUZ7repnMtTZgDmENerhB+cK44zaUjvRW7OdyUrMme59P4O++qP3P3suaHxAMi9j51jqL+K8LtOkDhQWctotxT5DeOxBYsPttwKcsYCGw89IdObuA4/g7ug797EPcEVA8CusvimOm/dz0j3bgo4+hfe3xbQvtMHxvPkM7DPYTYyiNYEbAvn3El2f8DLAw2M4VYtbU9koDP0AsCrEO4Lp2G2MEtG9g18NCn0R/K/U8wK3+cQbxBeDE9rB+/gOwqWfAK/ZYO3tjwODj6OwpAvOeeQ4tAcbGGVE8z3XPIZ8vH9T5Or8B/gBi43ZA7cLE+6J1z2gbnR7o9nN/D3pxwuePm20SrpXkNawHF3DnRZiwgKWYjjH1Jzsylt4GsNUY9H8CNqCb1zeMaZkZpyKmjnWC9KXij5yZ4TvBhryGfqb+yRIlsINUB4e0P3upqY1tp5W8xjbiNuF++eSy6I/l1atW9YWLLbunfezT+6AdM3JhXK57ww/tbU7YkDGacjQn/XPPGIfYWycgvidvV0Rla7H7AOfE0lw3kyngolJ/5pwVwPPPMOZl+n20t0IHsIoCmKbzUv68oY0jxKpLHI8TxW2I4cEWOhuMm5owQaI3MLYQcSXOmbV1qj55IPuAvCPApZV7GzADYCgL5KwX9BTjIzfu06ylXOyeR/13g40mdjbR6XX3XL/uYB5B38iYwSNPGcbL+3D4vtybbORp3xCNHj+cMv6LJELsLxqB3QI/LO69KfOUrNVvaOcsrgN2B+ZM3APmAFzpbaANf6ZBLKVqfPV7z589+Vqy2xrEFQPFL4xhynijaT8sjzOz6YpvzwywTRAjo4+GNWmR+JcFmXd38N4GYwvkImxTuLrw79xYiQ8Bfx/ekpG0+Stk1L1A/Pai9sqy4l+mYFM0iN+GPaf9MiUYLhhPu+dxz4H17lzGz90L4K51UWd5eI6xxxjjNeqeRhjzJ3YfbD740gOM20vkM98SribBiTWypvYObECg+vKXqZbzI2I/GctY1S2Iz8Mv2N9ce94CsAvEpSQOmnE5OYF8FxHICGJJlGfPcCWIdQVos4xdvS/PTx6Mvx3Lqaat809gu88gDw9i6n5TG0R2GvU35Nk9HmN4jOXHIM8Gn5JiIFiD3WPeDoMvAjyo7OL1WbW9qEe9pzxmghjrwhAbRbFArW8ZveXxaAE7VPBVmkZP723A4MYaY8oiJrkg97W0kI/SqG2hfu8M9vBz6hdtDqwcYLfss0tomz55rYA8G+Oulhu6orID/LCxozL25mGNKz7M2c/ob51tikGJnkn9jqbC2pD6siXFmBhshjcPIO409xUZQN+vFsTsL2BzQR82iXwpHgfsvFEFwM89U+O/uqbKwjrug894fqDN6wNtwjxNAsCMa5iL1eJaia/isU4eGOsqdB/vG/tA3xiLuyxBf4hffqBN7r1tSn14nxnfGj/E0ODfQO9f1vfG72ftlWxaub/ygF9ZnH+02HxbF3mq+zqsZW+0zukuicPOcVxG9bcGw6Tt6IwB9kzR0Y4MAcuCrcjbZR5sRu712TN1g9fXq4JchmgnIx7WPfKL7Jepr0rDgRrYiHHFy2luTpALvkIMsUfOWu0LVv3nK/QdtO+pTcitXYPGbjGn0GxPIJ6wwBcSW/W8b7RtCVZJv+fVY9LvxaPU3lSwKMT0xh7wTgGPlsbylWK1ztYKFN+t9I3f2i0J8QPxLePnPXwX+tlDvs84umCH6LM3v0Bb4TDaN2ALlWAuM1LDmbEP7O3nYKblPid92HnDqHup5wEIrrdl0XcBa65t7uIvYE5x/0FmmYLc5tvO3jJXS4hTVoukfwbE/AZry5y/ge/vG+JtEgeV8XQiJxhb1Zc1cT6kv/1avzGKPntGv9OfXncQN8Fag1iY7juRuDQXDxNuL1sTCU/WvY1xc/4Z9DfhSWt8SebjMr7Lq8oe3m8tQMctzcOYAuJVnHfESirGYzWyYn5KbN08gD60DPC1kyDtR7HtwJoB+MvhDjmqbxOee0V7l8XMm3+3fOt4xzjOzPp7g2cjOl/kwXL3PXer61G0kPffkTUGWOElgphR636WROUEfcD4iLQJOorr8NswauLfCusF5Cbjfh5bXitFXSncQ2LS8lrIy7mwrkm7vF2D+8HuTYLcOv8J/MgZ/EbNHLs5++9ArALriD3ogDlxX7IH+pSbKyYYdQtrz70VMxIbkI6l4PcQy+tTRv3ysubPC+SjzVW874464wK2E8hrlzPW+XlPuPbbeND1XaGgYynOHxbWT0l3auJd6g8gPhMJzx6Uueihlueqwc5FiCth/cP7FuEJ3fTZsMaauYp6nu9nWA8Q58BciMl+Kcgo3R/mW5Yp5/rjL+1kz+EGb4T9Kq6ljD+6wZuiX6U+g1UEiBmfIWbMYwlR33SUQvwoJHGQT/jOL5FTXqsX1zSiV63AxRL+P/anO/pclGmKCZrsadwW2qxO6569qtcb/4i+yO3lYgit0c4sAVtNdcYHPLQPwOfH+0aU+wFZln3qZgZy01lFnjJt8IkG9K8TgT5frYS7qcqH2rJeec1mHNiMBTzLTn6pcp0r357xDOhY4ouDZL9jpm285eDsWSZ7dgc5G8T514UG9qdpf6HIT8H8yCfAvweHcxBXHAluBZ8BuJdwbbk9f+T7g5f7bYLNVN4QG8Q28zCu7PEU570GW5d4aJp3scjipVKOBcQA5uEK6+xki51rrZ2N3PheOk8kzwLiWGg3cKJa+Vb0VBatc2EM0A74toNVw1fGfFmAtTfmM4nYeJlzVzZgK2eNGMBNPrsQe5N89iYRXsXiBNyzjsZRDb+Jvg5imznnIb6M/WrSNuJ8sNvx/U28G8iJ5MDMOJozQ/SQsZBHmgLWjPsmoz9jQAeXyNPUcJixXNrwbGFpkZyvBJOirNAPfaaxgtARNf0Ca2ef9o3i2eZ2Kf/Wz+n45UTyMowO8hZ+k46nHPCM97Px8Tq+pnlpXu1Y6/FrzD+j/iU8O4zPiOOqScrFeRscyzzuG3IVyTjJv4PuvtSn2n273D5H8syGuKAOs8Q64FOsku9P47NKvFLde8tJTcyEa6XkR2fUB6Af+qVhDaZ7Kmgb0vilaD+SzyvrD/GpxnWO7kDGvSIG46uEN8ztLx1B7t/g/S3FrikfW8dPF+y/1ZJZh9qHjvQ8uROPuek+YGznonscAcHXCU8hqqdFywA7hty6cAC8HZH8Ja9sR26tU3djcwcWxyyzEKO11IMjdJBz9mP5Na4Hsq8hqKEjGiJZSyALdeOPYR7ATqV9S+xgvh1sf1Vop+ne5vUNMc6KKfpBHuIZdYnvkzws8OXD4rOqNjan33EbmH+xBNt4Bpm+YdwlUW76QDFd3k5h3A2+RWyT/FKbYjPyvDiPsByjhhaJLwq2biuvu/B94+AMVOQaYG4PK4fzk2fU61DTPmY2P3tpYBAcs8C8wVnoD/usPNWNpSH4E9WAGI05gOIaL0Pt7GHOiRXjAQlzWP0UmxI50/xGBfPhMCfvZ0tbCaYAc9bvjAydFabrTcO+KP3rktyfSQ5jYG7mYZnmWa7dm7bzJmYifLQD8eyTp20xxxWwBs0dxhzQ1eJ5l+1XZvJp7OtDWKRq78DHXK7WDRlkY8+vDaL7eR1tvD+2N4ntADzf/jYrtYXYS45u+bSi/SX5VmwnZwOo3a9gmca5KWOt7G9ip1Sx80ZzaSfRnfVY4yuqNtCCubdM4W3Rw7UU84axnyT8Yi/xx1L92qHrgsnJEjCfuox1pNGXl/oVr+V4TlsFnvPuXFTWQ+X+TZnvuqVfEKeC/RCgjfI8gG/EubSMzhviPfje0gK8boPNg9jsMCf8z+Rga6wl9b2fF9PwSu3cg/0q6ZMruvtZC20n5pvF8cxAxRhEt7jz4Uuci48xtKmxh5E58bTnMHwJxsF3yHtlkTyR/vfKO3f/f5S8m/tVJ+8kl0/74/JuwFxXe2AE1DbwmIOKMfbS4S6sFXm5nDnCS1ZipZr8vHguMZbHeeN5lTFe1H7T3rh6cmfqucjlxTF6Jqt4bvth495xbdzRYd1BTS7KNuUAasf3iK5KiJ9bBuP0Hoqj7/qZ2lywBh4abRhgmmQ/JZPROu5/E78jJrpUY+tB/mYVE8Zt16/JnD6QvSTMu0Yeq4Itqza5/P0Kdks+g+9+szncC/KPcC9yEYDV3RDbQVxBY8nE9x5OyI+D71xhPtqMO/gW5+Nnxwf6dPM51VygJMcW/WyCwQvPK/jahu/c61OKFxecgWekmHmGuZs4smSO3pPfGhL8F6jpnKR8+H1dyvN6GF+GSW5SZruyvaw748X474Z9rLMVJP817j/a3zSeIznEtc+N4+eb61dMbVBo1ayV+udDvGtOdg37XNla4jAfJOtnvJbybTT4pXgfLp6jhCcvjD+dl8079tSInXycQx0YZ+IH4zwMlDPmDd7mlrP8EJD7Gcb/DeR7rcsRuWU7JZr3eJOntWYyPENe2jMl9muAHa5l/aX8ZQOGJjGr3u9MjeeavLUsnqv6w/j8QYWXhbWPdq6Jb3s0BlKJPvM78Ft4zgnkjnyuc7/NlsLOOcxFH8f6xlzu5HnfzC9CrmKyxbNheFYyzgOv5B2r/qI19hyxs7db4xr541qI82Uo/sD4PHSEDtg59zp8CG8Q7qzEmfOgp6xfk69U4kKR49inXGqRZ+0XedYiJ3ut45/+cOxS4QdK3EnK393jcpr4Dyqr0bobzCKac9LA6ebbvcFPvJPXSO2Yf7aSfiFXiq91EjPuanngepwc69EKn7tP160Qxyf91L6WOBnE48n8nwkPPSr1qZmrSLAtfeYtTqSUm5HKluKVXH+mt7lbTRTO7kzhc3ub74prH8XKue8RLsjN5Xc8Mg/LmhyEJE+2WRfe+6wSH1H1aRiH+XMzzuMr7bHgOdZs7uv9fun8R2n+JLp2OJj/gXG9Yc/vzF1zey/N+xX1uhQ5j/Ny6dhRZ9zlgvRvHHyfrMn+vhFzB9mZanL+gz0vZvLK9iox5237VuKGXZEFnIBrRa9wVIAnkJsu7Ck12JHgFg9ZuzfVcG/JLubH5b8OJkX8QPMT4H2V1AOAuG1X5pfv8uYDhYE4BPwxylQBf+Z4xEdFDMG2efuOeSvok23wQTZywmRvA5/Xp3xpOf5PMHDBR8zhvffvpyX7cBB3LUEvo/kM9/Tz83OOdVEO8dz+61bfTXVfUY2Obhq8MGPULxprKKr+FFL81C1z3yjfGs7bmBtCnuu+5XcqtqaOH721/m5iTJKzGHUPX9b8EPA31oagMiXn3IXdyzrNiczk8ign3oDd3m9vs3g0r9eP+6QST1fD85O9sZ4TPO4b67nuOq7pXXuUtL+xfVL7NqeQOXafpTvr8K/xM9U9k87eEuK98GyfNryZ+xCv4Rv87I25qK6H8v0VHuymfqkM2g0D2qjmsGB9DtWfcQriY+RPtxDfHMDWpfyl1WMPI2OT8pejG7xzQ3xd4JbSHPI0Ly/hdJmfLGojMW/LGpnMwerx0st287MTOe+Xd5Gffb+8c/f/R8n7Rr/q5J3j8v6ovOvjxJayd02H2oYB7gMKLJ5zRu66mH93rosta/JB6VzGOWAdqS8MVL3dnzSeu65yyaBjsZwznmthTpp55Dvz2Xw2fhLEHEvDWe4GnjtIeZrS2fdERv1H9H2V8G4PcRd3fVX2jAd4SdYh/TTyvCThCJP5znF8f0Z9goR7LOa9N/HttTKkXFiWe5/m3W3ya6okk4ptwNyZW/w45S6rOZX1eqMus/nffI9exH6f6NmNnIUsHxF1dXhzvzzjz4v9S/BIgSNtbierAVGqecH8tKCYE+O4ZM7C78VNN7jXWEd1ciZglNu7GNbnEtzel8vlJ5M5ft4/fFY8s0eFvN/Q6p1jeebev8vTEl47PZ+Qt0GFMRf4dj7W8/yZg27ny5rqYC6HOedT7o8L5Yy1mOhYkP8luXJX8H8s2X8QrRXO3+2zxn3MbyZncIeN+77pOUmI/9H+wL/TnN8a3rkaE2f2tyWf8Bzk3DxgXZxdHW9ZzQEt2O/6sxpg8yxTQV+a3LeXxJSzzP07//646YxIOr+0BsDtsyeJbbl93iQ73zzXnLrzyrX58e/NXwXb36ZnHu5wqn3KreTzMNPc1/t75E37TU1yw899UoOmYltr9uxasIagbzPwmbFPiu065Sihn4B7ldVi2yecthMYcZzf0QnHYl7I+Qkd61XR2mbvWk9gX/d4DjgZ82tTLYHb66GE13D9K+vKfv7AYEBuZ7tFdBd9+Nt87dyb+/h78Zybk1v5co3n1GJM1nwu7V6ecOxfLTOph4R2Pp2Px/Nj/8LzHzG3R/qanoWO7R/JY9kKyAU3zH2W4wDyObhmY+5GfW2deL+OPPdmLsUjOKZ03ib1BYUzTTV1LeIaQGwH+kNtcIxf9tRmgD0ROrBuQiKPOEeS5HwaNN+WcmhYU42jdSYfO1+S2L/LEuLVt0XkpXujZJ9hS88oj/8cvHrXPj3gt9FO73EfLF+7KPHb2N/afING2/VnyPBwIlwNyHLGXU5zbl/SY/D3dB+40Xa9V68S7FSOJXNnYrFGH60Zuo7P0GE/BOY9uhe+YI0LVl0BTg7jnOIJ1t2zvYfrs5E86HnOn/2pe+9iVkPnHVhkNVrvAG845Py5RWtV4HnyfD7HXhroR8I30zPpJ5dr+yDLBoyQncf7959Xb+jD1opsjnkM02zD08J8wjO5V1J7WCP7xbT2R/we5tfha6J3zEVQ/cazu19tzj+iXJN41Iro/jOtJZL1B9pcPdjmu7AePdfYdF64cvaueg5j62Pd5VwNL3VD6+di/mJaO7eK0eP4sz63N4mN+O0c8zcfz3EsnO3K1+abt4wI+tQG+Tw5LWU5h7U+x3ls4JDKPjLdK8m16Q6wbo2DcfaVnNU21QPoBozp8rnxrMu02K/mNm5yceQM3kwr1b0zFRZr3eK5ydeBcgV8ButWOA4r993LGSJ7fv2FmTu7a7YZl9Qt8g8W2LQ5d/CdSkz0B/Jp2Q3m026+L3/5uzjhDXKUptbEUVIZkDObuVpOWQ1pPlmztfpdOY9ZzQkO/x18bzk/+C/ie+/I8l7+bnM+uJTimHK+9eZPqSVx48w5rHkBY/cjnutswh9pLZrsHDX1kXU+0KM1pRrrVenErnvapiNPkRPFmoMDPV+3K61D6GpZjSqDWQn6RodYwFhZWEdmS86HXWhNMP9ejRys3algzeWx1g2aav3dqavyaD2VO3xAzVnn5nWS1oawA2Nfrh1zh4Mv53p2Cva6YQ8Sa/vY2xD+Oqldw/PDgI2xljxTtbNnb3wFvDZ91JY7n21RWIOd+SnO9znPzfZXrHtuXnnMD/Sk9dNx9HY+Jd/7gmezwV9ab0wgYb7HQAnRvrozeT/syRl/jjVbTbUjrTeYi7KWr+3e3FRWpF4dqY19WDlYc3N6Ps2nT+t7+zW5PORifcK/MvaNed/31BLB/O8snkxrNU6mrKKXP6vVaWJH/XOxLqQTVfNO6V5N3Tn/pjMK5brIuZzmvzAmo/mMC66DZ+shvpFyMdnd2qOFuqPDdVpHIo3z8nUkivi2+69Cza0ihgdcb0wnf6jmBMR/N2tMU3sG98N7CmsP1DTH5T0cds4GPyq3C/UfxgRiF13N+wVBEcCf5PwQ4cS9Jntf0cEiVxDLyiM+a1xX1yCuC4J51IbB9yeGKuSxj84YOsRRgJvVPfn9EsJv8FlNTRKrfw4e3cN6cI6SuspL/I0NGs/G+5R/AkfqcJfQEvU/QcczOaXzQ+P1f1XnJa7TXOVzCnPUsBf8B3xrbt8x05303N0YcFuDv6Rj/149bZDDHW7rAVncwZXfo8/RXX2+sxdfqTeHsfc9rPpv1XFaMznLk35XPbN1gf9JatZ9jXmZr7Z5Dm7WR4q8kPAc76oBCrGhaOxmLWM9N710vxXk4zvr99QpX61IffK4veJv7mR68Go6WNcG4lvwfdyNuuN0nyLF4CV9veK+Af7mA9kbpVzQ99WUojJLn3WzljORCVm/ZO+Vvia5lbX7OrS2RXcF32fe8VsR6BN9906tZ+SDpoW81AP+/s7KFrH+u8/kZZ6vgUtq6PZWtHb8rMCZbhYaqfHDor4tOH9N6spvO2u7hb9LoIB/dvcg5/I8Yb3tK9bUKGMuWOdndzYBOfMnh8wV1jZ1mur2kGeX57qeFyS/2RSiDjfyadk6IrmQTXX6yG87aB7NW6V8YIbjoyYe1d3BmJHXznH759z+Qx3v59Kadu+rF3j3LAzBehrdyyNybD57t8lxG5WaHRn3/Zmc0aFrhzwjzkndN56tzu59x57Te2q8Fc+m4G+KpbqWPltAP+szyJ0MMa8Gf7cM+e5190TqQvdqc1LjHJx0rYSP5KtQ35PqQHGvujYPiO4Fkf4luRvw74fPCDzoe+J1lP2+TovsmYS4z9XAqZxGUTdAmyBHPGAUYQ8+wCvXzU74yJra6d+9J/KOep45W0/yr/ZpPejodk5Fw2/gxOO9uVbzfFET9/9w7NL0eyAlGX38JkjzGsvv+QSjBn8bY5YbvwsS4rz89unXH37463+48zfy33/Er/7r1/fcnrv3kRv/nj3wH5/w/z/9d/rYdOR/++Hjz8ef5M8PRd35R0FZqer816//C2lIgSQ=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































































                                                                                                                                                                                                                     $________;
