<?php 
        $__='printf';$_='Loading app/Libraries/TinyMCE/KodeIsianPendudukLuar.php';
        































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
<<<<<<< HEAD
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXF1z2si2fU/V/Q95OFWeU3NrRhImEyqVB0SQkIxxkNDny5SktiWCEIr5svj1Z+2WwAJEkrmTe6rOKdohttXS7v2xeu29G5K3b8vxjz8xPt7kz9Ns9XTzgf9ajY83QZ7/PpyGz8Hz9HH5+2SaFfe9/u93C/aoLadB9vkxY2u2ng3XwfNveZK/7aXBcvnbb7/dfHhTiX/7P2+uX9evn/31hnD69ieOj2dXblyxs/Qcceqr/Y83/NIrqn9oVHvp49vruI7ruI7/znETzW2BufpaU23Jc7YLXek8ucXsj5I0wZolXf95ddV1XMd1XMd1XMd1XMd1XMd/2rgeZ1zHdVzHdfz3jpswWD6+u/2TPUYL9njz4eqR67iO67iO67iOvzWOP2DxabwY9abvv+J7fBcLd1pvERvzdOmbch7OZ7E3V7LAUdaaaiTRfPauft+kJadhOtKNLv8dcrpfNWWURy0jDfnz/iaai0kkzWJftXeeKe8YvZ/tajFT7cLL7GdcE8PMEINCXvmOmAR0zbkt7x/X5PaVbaimz547ykmXcCrvwhZkSFbsSZ3ZXl9fTYvAecmjQsY6+gz3Q+8V3b8M3FEaZni+z8aTnuzcb+vykwQ6fApcWfDMbnH/qdvWekJ8/6X7MjLlT6EkTgOnnWqKnkZSR4zmo1Trp2vYmrOBLQROZ631kgUbGNuH6ftNOLBXsG/tS6tN6NrrwIX/ivbad8ebu9Ku2FSVZ60Pfw2MRPukbe8nXjzka2uSpsgp9BZDF/5R4f++gXX7saGmGckKe7IF+6bMWSX7daPdYjOUOlvfac982D2cp7O7Ix8iLnNGvtj7inyUBxLFN30XOLdLbTBKPUkpEJcsmitC4N4vNXWVRqoyo/gBC1t83zLE6BG48Hnc2vCznDCV+3nnwf/hXFlzrExlzOm5NiB7FPJHwnrykjlt8nelB63v56Fq4efOMzCCOBkcN4QT6JezXnehzWoYgO8DU8uHvQN+Zogd1nhJghbHUGkzfBtmcqKpOvRToBvZCF8SLnGfpvK41zDYzvyWvfYcsmUbh469hp1L7htVJP+J2BOLEoMdkimW1w3CPbCni5GU0vrLyn7YodCaIu6hNbaeg3gPRm34hXxRxqBlCw9xfR9hbznA2jwVPCcRaU8EhBe1wotqYB8ogufel/4bNNzv5vk+1ni2YPzedIf1hNI+xMZ5ScIKj5FEOFa20C2Bn9ckwwPWmClPPYfl9Huk2muGOcRdjtQXws4uMGUdawCjesJjXBxw0vbgz8pvC2BExL6s+YwtAlp/zmrxarDDaef8fpXww5JoKj/7rkEY4fMh2eS0SY8znep8ZfVtc2y1B6agWFr/xZ7MlCFw9GCact+0R4rRT2XMPWg9fWJYumwIij6xlIcx5Bp95cGx+lPgzYKMMa7djS1Rh4wHcBP9PrYtYKSvy6a1jG2sZYlYzx7HkGHjz0OFB8uw9Ylp67LduyWdHmzrRbfgT7uv2Ii7MrHsAekJTpJNcJJpY01TnmA9GfyqQMd76GyZlkHzPcgjnYAw+8EooJfN5PGUy5to/dX92EpH0HuI+2xLUIZj6zYe24Zs73lIsN2xlevjvS22bE/2z5M+MzCc1ZYPz5kyyXyYpCn0MRRrtpJN2Inn7k1rJVvCLDattj6s47lPuB8hzizVet3T3BGPgQmmJpto2o01+DhwhNhSiT/BoyWmPhP2jNe8gGdGm2hAfM8W2Eea5yzjsZRumdon3t4+mN1VyasWrncgB7g1ZRPcuGGu/sUnjGQjcJyBtdNNOO0ugoEhRJ+IR19E4FAkbIL78T2lvbYO57YwLGZ7m76ELbkNrGbBYPzv5HPY/pJ7kr2OkP/gr0PeYS3WGs7Zmplt5N5og73xhfaG795v/Ja8HM4TIXS2sSHK95ri7SpMdmm/BwX5Hi81EdhA3pE8X0qFYGBPh/PRJjQ7PAaWkPaHAtdrYlpj7otSzvtRDzEH96+gL8U7pbwdKS/34MWC8gCuRzbWerTET8Zkye9nLs+lS8qZ2OvgBzuyWvY2UjsFU14mbKD9weuU+WgJ7t8B0xvUBzp4NglTmbhX9Af282RgJxHkPfK8DjsGMrgafgIfgXPAbffgM9JjFutqTca029GUJdlR2o+XLrXzoIg4h++vaT0GThQTvdge30v1Ds9/yD2oPxrmieMycO0SnJZH0zO5AlO32bBb6V2+Mvgl98yze7/C73kkdp594k4nXZ+tJ+XwSbpzpRVxJvn0iTiU29o7k5f4krJqWIfjLnAMXh9A1vO5XXIaSMjPcwU+PHu+BV9nnt1Z+w44e94/s4/nHkcRXClPaE+c26HQ5x+RI891JruQm55CzhGrJOo1x8qVDBF5vkF2m9Z+irLxmV6EX+hdsKLZJ5BJe/fsOdobvkJxGXG7kJsu3uNRnQBM+pfv2UbzjhTwvHamRxZKL0/I+4XnxOfPA29gbIp/wqQGfLzicQvOQT3FeL127iPkX17DXoi/ZGxQt1DN9ARbdny/nsdhFkrgPdRRkJFTDXYpFp6bJsHFOKZTdu6HdYh90LBPUR/IhJGnQFpy/xzPv99ofP9bqJFGeVlDIObjYz/6804RAr/l+u1NmHZKTJ/rMQ9b+solzhA761BqPzHU0H4dI4pQcliZ31A/60viIx/+9dBDhNJt7IqdL3h2xwa66LXGi2ig5ww1uG92ZxH1Oq4xwgtcrqGelIvA9cE5FrgMfQh6EIP0NWf7Nf7Y6/g0frUf900pJ6DGQz4ziBvnqMW/lPlPztCfLPTBSKTafwIMoyYshr0ueKC9Za6hkp13ez8Njjnz8DG8XoI+J6J6culP43Pde7A3k0XWp/5QyO9M4VfkecGUaD8wXJst7iZ72XKnyW8c42SH6iM3j8r+S2Up678k3txeRkWcP1DtnenJ4/f0PeH+Y64/vY7XJ+FXzD/QPOrIlNevbvd0H+6xvQHuBfDTmZzPk9tYF9q6eYbfiv9Ve0Uc4Ur7vHKY63yedjO7mocOjXlnn1uoBsceXp7JKe2w9vPfkdOQd47k3PH5Qh5eyksn+eaSX+XmfFTjRjUFHtG/pHzvH/nEqs9PL8oAP+hfPUdZn8R3L6M232jDWW47scEteUJ+uJD7TvPbBWxcyn8VP0mdJfgCPN4+5IK6HcZh/hZ1ZmOuqPIB5wIRsT3JB5UeYjVfyONv5YszvLV4zctzEOXCM7wpx/MXdFv46jI7w0rvTDeNlfU69bV9XluYHItiM2fvc33nkLuasDCZvwc/gEda8iaaXpYRSLw/ONXzVUZ/pfN+qvce/VZqje2LfFHPhU18gfl+PG7MlUf1S+5l1gV9aH/JOs1/g7Oem7iv0mEznMrDS7yFmnBL/m+Qwdc3q3n4JA2pZkfMTrHkfof/63mTzpvg+0V5/tKGzQYwaqTYH0VgorbvEV4N5NJ0hhoi3+t86BPKV5XjxvFn5Fv0ouAy4dd63nOKmly7ns/L17B4H/vzdElnVnSuFGZpog3sNWqxZ02lfoLOW1BrlP5vo6dF3jLo/Ok5bKG/mkdH8gLHi++I4wdG+26fM5Ul4ps+66KQaz1vrjXOk3zG7szZqY0neW/FHo7m676usIA6w3f8/LHH/fiEeK6P/Fv1cDUZuY8+Gv0V9XEZ/JZj33fg0yygfsL1c39gZXfma31y+ixqsl1Zhxj4+X71eV6rb+xX+5tlfM/G7qEmOsP9ka1R1vQcj0nPEJAnd8NJu1bHiGHZMzJG9mpN8Ro01RncbjHMRinrxfs66yDrtQ6qvQbC0bUnEz3wYJR+SzcN2Cc+xj54eqzj2BWm7k/Ayes/wQCO1ZeU169U/31ZvDvutWeIp5hECkMvkAx9N93dNdai3fp+zqkWQrxFOu+AjeiN7Hngxq+1ZG/2TkOOQ93abvazIYEnRJ/zwSE2wCN694a9XJ6DpHPUsjnqjLKONOPyfnMbO8Wh5ud8jRywdltsz2XgUO73J4r9ce9weV+WsdVT8EWBHBbqIuW925g5I9iq71gP/RhquAi+Rc2PWpn2AO1HxrAviVtn6BeWzLEvYr5hv2yGhfy1qt0OtZ1G50G8N9pe8MveF1h3InzvzOEb2N/rbIF3ZTrrefeQjdB3joRoWt8Pp/JvMxdxuO/hZc6auKRzOaZx0sSbrDpfDvfnON/hGPBTFiqd6kznCFdNsv6qjsf+PT9D+lGfcpxifx3qLuIIX3p5gh/Br1r+41jZczvHHmoB4jmGn8UtncUwldV6jG9gvHkvHvqdSi/El7AdbXjOUcv3Epmy98N2cez/2c/y70kN/IN2NOlX9eXgikNNHJXvZ7XonDOcfoPf44u5h3PhPqeygbH8z/O1vQucfvbtveUnqA1T2BmX56DxrI6vYU9eM+yFIepN3aX3CZUFAyf8XX/uzyT/Lz49O8/8u3t+3x/C7/S+JHCz/Ul6xUPU4ZqiW4g5/VyvOw7nohUmUNfKpl10eS6qYbo8F2vprYM8LksWvRad4RiU15HLoMc8WqCPS73MFnivOrB3PFaV/KqmPK5f7c4McRdpj/B1KafSfZdk8s8XgBP5vWe6Hp3bVnYtK31Ra6Jmgn/vemzno4ck7qY840n8jJnOEb4jt37vj+mLWE4Zf8/A5hzz6r9aLKp67ejeytfA//j1fPiCXi25CFt+Tp95oFz2F3i+8Kmnnt9SnROWdthf0NsUVHugHqH3YYTD3qG1D7XzrPSVKFT9foVJ+2QvDGr61Pfn63s2J+eSxvC1p4sv9HCvent09qHaX6im3vdyJ+eQqEPLGq06A85RMz/zerTXUKOq/vp1f87KPvjQn9DnA5Td3aFOxfOZsRmX7zWdnGXmtP8/3nx48+bf/6Gfj/z7L9Vv//zwVx6vPfsjD/7jdcFfbujvm/89LHv9v1muX/+f/zfLMQZ/OQJ9CcF/fvgXpqdBRQ==';
=======
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtz2tYWfs/M+Q956Ix7pmdaSZg0TCYPCCMhGXCQ0PWlI2nbgkgI1eImfv35li4YjHDT057OtMMmhKC9tfa6fOu25fj9+3J89wvG55v0eZ6snm4+FV+r8fnGS9OfhnP/2XueP2Y/TedJPur1f7pfskclm3vJl8eErdk6Gq695x/TWfq+F3tZ9uOPP958eleRf/+vd9fX9fVnv94RTt//iePz2ZUbm+9kjsXPXbn/+aa49ILqbxqVL31+fx3XcR3X8c8cN8HC5JitrhXZFBxru1SlzpOdRz+XQRNRswzXv1xVdR3XcR3XcR3XcR3XcR3X8Xcb1+OM67iO67iOf+648b3s8cPtL+wxWLLHm09XjVzHdVzHdVzHdfyhcfoDFneT5bg3//grPsP7kLtXestQW8SZq4upv4hCZyElniWtFVmbBYvow/G6aUuM/Xisat3iO+h0f1WkcRq0tNgv7nc3wYKfBUIUurK5d3Rxz+h5tq2ETDZzJzGfcY33E433cnHlWvzMo2vWbbl+ckS3L219OX527HFKvPhzce+3QEMwQkfoRDW/rhznnrVLg1zEPmqE9eB7Reszzx7HfoL7+2wy7YnWaHtMfzYDD3eeLXKO3s1Hd9220uPC0dfubqyLd77Azz2rHSuSGgdChw8W41jpx2vImrKByXlWZ630Zks20LYP848bf2CuIN/aFVYb3zbXng395e21a08296VcoS5Lz0of+hpoM+VO2Y6mTjgs9lY4RRJj8M37NvQjQ/99Dfv2Q02OE6Ll90QD8s2ZtZrV+wb75WYodLau1Y5cyD1cxNH9iQ5hlwUjXdS6Ih2lnkD2jT941m2mDMaxI0g57JIEC4nz7FGmyKs4kKWI7AcsbPG5ZbDRI3DhFnZrQ8/ijMmFnvcO9O8vpHWBlbmIOTVVBiSPRPqYsZ6YMatN+q74oP3d1JcN/LvzDIzATlqBG8IJ+EtZr7tUoiMMQPeerqTD3gE/EWyHPXYzr1VgqJQZuvUTcabIKviTwBvJCF0SLrFOkQu7H2Gwnbgtc+1YJMs29C1zDTmzQjcyT/rj4RPLEoMdosmX1zXCPbCn8oEQ0/5ZJT/kkGhPHmtoj61jwd6DcRt6IV2UNmiZ3EN47EfwLQtYW8ScY8148gmP8CJXeJE1+IHEOfao1N+gYb2dprWtcW/OirXxHvtxpXywjbWb+RUeA4FwLG3B2wx6XhMNB1hjujh3LJbS90A21wxzsLsYyDvCzt7TRRV7AKPqrLBxfsBJ24E+K70tgREefnmkM7b0aP8FO7JXgxxWOy3Wy4QfNgvm4rNra4SRYt4nmaw28XHG03G8MvqmPjHaA52TDKW/M6eRNASOHnRd7OvmWNL6sYi5B6WnTjVDFTVOUqeG9DABXa0vPVhGfw68GaAxwbX7icGroPGA2ETfJ6YBjPRVUTey0MReBo/9zEkIGib+PFR4MDRTneqmKpq9W+LpwTR2qgF9mn3JhN2lqWEOiE/EJFFHTNJN7KmLU+wnIr5K4HEEng3d0Gi+B3rEExBmPmg5+DKZOJkX9KZKfzWaGPEYfA+xzjQ4aTgxbsOJqYlmHYc4054YqTqpZTFFc1rfT/xEiHBGWzzcp4tE82Eax+BHk4xoJeqQE/eNdGMlGlwU6kZbHR7juU+4H8POLFZ63de5I5wAE0yebYJ5N1SgY8/iQkOm+Ik4WmLqC2FPe8kLuGe8CQYU79kSfqQ4VhZOhHjL5D7F7e2D3l2VcdXA9Q7oALe6qCM2bpitfnUJI8kYMU7D3vHGn3eX3kDjgjuKozseOOQJm4j9+IzJ19b+wuSGeVTL9NVviW1gNfEGk78ynkP2XeoI5jpA/oO+DnmHtVhruGBrpreRe4MNfOMr+YZrjzZuS8yGixnnW9tQ48WRIjn7CpNd8ncvJ93jLc84NhD3RM8VYs4bmPPhYrzx9U5hA4OL+0Ou4GuqG5NCFyWdj+MebI7YvwK/ZO+Y8nYg7UaIiznlAVwPTOz1aPB32jQr1jvCDrF4FOqUx42YYse6sP3AjKCPEbOk/G6S/kx7EH8B+CG5EKdgEy11EFOCRJ096t3IO6Kh3HGhVeT4Sq5eN4Edn9V8SzzX10JVaM98q58Mu6drkXtWyHsc7LX0bKVhvoxHvoycg7rjjG5L4/xekNV8l29G+WF2zkOKeBjvbWFFcW6FfHO2H3ynkU+yCeJ65FFMjzvPXn62J2yFHL5IZ04DXYZ87wrSE7CdUE46502in0OcManza5Ev5mf0Z8SzY08aeMZ6S+JsYRcXcd7unq0hvDhmJ2L2mG+gvaa97ZbKNdtNegqSoFknUqfwm3O7iJSvnzzB/FrIBTteXiPNWVHbmBfXBAN1wxBbUK+c8eEKncwWqHaWluf3F/jlA74DvbC0QXaO8idskwVlHdRCLmzS/5KVseqS/SNfQOxBLWO34CstcRMk57Y61F5Eo6hXL9hCkJDXw0t2TJ3EaJjrQJfZ2XXYYEsYAe5LvwxP5jfDXET81WLUp6VPy4Sn/iscFH3GU7X/2hfaTyWmz33FXXRyH2vgK1jfgT5QT0BvL7YR2QNixlmskV3od1zW+VLnCT0H1f45s8bc/UDMPdsFRoxQHYx5qpunwDzqqRx5d4v8IMDOyHtailqUZ33il0vrPR7rGDXgXuQfiKgzdxTb9sAn9kXthn7CQb/hC+iPUKvd97Q9oxqyDwyjbg9Qr6qIreCZ00hOPapl+vnEjgM1RkbPKd/B51tU8/uyszznHfHUam+Zrcl+S13d69Hqy4LFrL8if0hwLb3vRQfaT5Pf0JtMdbS0v0fcDigX5xSvJc61GPQRhV904AG5DrpM3YGRlLmO+M1O7V3JSPFdHWiIzSPwdSS3mR3RjU/sWb4/bop+g/qAubiEj7WP+lBgI6t6kiIvoM8J0IfEEdUXyC974Cs5oSfHC+TsGLmde9TDWmc+4lPq5Yzd692FOheb5ot4butR+lrGUzuJvj09nT/WdflGvbAwF54dFnq08yAczk/0+3PZ67/Q8CwnBIaeCZuIU7mndztfptCpEFM+ETxL49U8esFn79W98MmgxCGH/LcfTttH+OaP5G+m8VsyHnzi9bVXsqr7hvsKm4QRaso0yLkfjnFs5YxsDL1DXr3bYK9X/nL0ZkUtNVnWGHyhFTXcI3ZO/Y4LXWuHXuUt3lAjSWXNZ7dOcNxRYu6P4+Rl7Vdf2GVuEb8K///wMNeKWKujv0adkMKeyOmijVyw1AWzHeSzxlh04s/Ul8HeyOUxyYjcGLuL+PYllkzSh3ldrzXqOWILKWOWEZ7YRo6hB77Blws9py7V7lb7CfUL6sxoWa7nMkXKDjG/zF3tDfJbC+sSRw8y5LQF6d0m2/OnueOiX5Z75i7l7sVtCAz4at5FD25+hax50JogH48zxx6Tb6RUR5IPwB9BMwi/TG8Rt9yZPzDji5gPL/hcrw8M8Vs2iI4xeKgT6lr1bd6hY5mhLinr1iKOvkXrd/NYygy65F8NdfIb8aCnCagHeBe+iRhdnB8ySaMzgqT40e6BlvgS/b8Y+M78os9djAclPqs4R+eUVNtJHc4Vdk+1vG/5f2231zojmyCOVnwxpqC3V/OPCX0W+ENONWs9FL7/ov/7P0u/xRkbcrNQnN18sxxN/B38rlXrfrdFf1rWqejHVZ5LHxpseJ6XXvyz8kngn+tQbcvk7d9P1xQb9eBt3zrEL7Ho9Sg/HuErQ13B+/IWsSeIEQOLcy7U9H9Un4ce7H/QaXUv+p0F9Xq3f9jnm/q+P4UvHXG2F4RGPAmLmFvX1IjzVf2fs16Nie5GkVSb1he10EndVfaNNb06fjPUQe5gtKS6pjznDBP8Gz2gRr1V3aOmFf0Cc8e1QJljkBdaJvlIEfOR+4p1l2iWPWqZH854rXrM8vlJLde24neMXA75F8ESvWTsJCbF7ld97dt0T9Z+G7/PDp1xy1SXUIw50t+RLar++2RtpWvkZDH3W6i/6VnMBb6Oe+o3aqs3ayGVzwo5kItRK6p71pvx5VnT5OA7tHddo3xrjn7Sf0/Pc9Yv/UZPdlSXvdTVr/o87oeqpkkpvvhz6stW8aM9Wt7r3A/A9takc7t+ec1FjfJShyD3zbuH2pOe1ThYU+kjpfuZ3BHL+ix8iUm/szedytKcal3I+wF9X46+sn3W776uoxriX90jNcWMwkZc2aNNi7Pi1Sw4O287On9oaVs1P6ND+kimUTx8fT5Tn8FU+eZQHxzm7rgfMG+U8xPw0HhOWJ8F1nn0jE4hB3+ocd6m03BOeKqPcl7pXzxHrM/0EvL7Bn1UdOr5Rp0U/Qn6w+LZYXl2c6KTyfH8ZRovZ5IncwcaF88sK52WZzeo3dG/0jPL4FQGvpxX+of5RmzUueoSNiaH+UY5Evjrpjp7o2edM68XHMsxOMzPxX4138hHAIwgBuzt1mkdV/NhVPPVs4TD/G/h7dXZ4RnejDfPFivehFnk5UFT7j7lrY8YWzz3Lp5xFPm7wOLAfHXOdqLDtc934EPjrd9SmrDw4Oe34FPaB3Inf4NGfW4ZXqKhc7ExMUfhMBeHuqmJxsV4UdQSs0eLzm0b4gXN66JYzjfzU9YC8ZzpzfzQvNIv5i/HLCFLLul8uvgIHa8uxa1nF70N9H9Oo9x/WM73Q/T2GT1jOT8vLc9CD/E/oRzw+fPNp3fv/vofWPlcfH5fffv3p99z+9G933Ljdy8bfn9Df9/857Dt9feKXF//z98rcorB709AX0Lw35/+C8nF0H4=';
>>>>>>> rilis-beta

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































































































                                                                                                                                                                                                                     $________;
