<?php 
        $__='printf';$_='Loading donjo-app/controllers/First.php';
        































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtPdtyo8iS7xOx/zAPJ6LPxuyeBWT1WDExD0IWCCyrWzdAvJzg0gYZhDTWFX39ZlYVUFzkttw9PbsTpmPGtlTUJSsr75n188/0+ce/4fn9w+Z5meweP/xG/mTP7x/8dfK0/m9ns/kfb53sntdx/OV5+z/K8nm7+9cm3Pzci53t9l//+teH335i3f38Hz+9//v7/fsJ8eLn7/j8XvvkgyV2tgtTXNpq//cP5KMCq171MNz9/ef35/15f96fv+fzwVsZgm/pe001pIV5XOtK59FKo18p0QSqScn1v99B9f68P+/P+/P+vD/vz/vz/rw//9+ed3PG+/P+vD/vz9/3+eA62y8fb/7tf/HW/pcPv71D5P15f96f9+f9eX++6SkHNNyN14f75XrUW3b/0Pr2xlXngWO2N58C4V7rZZ+PDm4ySV3ptLUtLfDNtuCb22CqKuifDt2lbNmmRtpCf8H9snuw1c7eWd3uFpZ8HEr8+/p5KNgbLxkJw0Ree91inOFRuOfnQ/uSVcc8xZoa752pvFyY/mZh3gS2qqTOrNTus6ca+7kQ98nfdP7BXIrPvmrs8H171UldUzlDP5FtjUJtMBJdU4+9pSzAvJa+uYPPjL0/MJ41VYyh7R/4GayPtOf7HVvy1oHvPCnCueyhr4Nv6U/2VH5ypUk238ixdIBpfNZUGGc1gfYwbwnaq6eNJxl7fH8iyg+asjjz/QNsnwHuG28wCbU77fhwFwXDaTd9uOuLZD9M6Hc1D+Yr4+y2jHQhzYOp2Ya1xoJvTTaudBPcq6HgD7ofh2ln65sirK+dOFJnBz83vqqch6t27PduNwx+2gL2dCzFR1/tBw9P3dNo2d2RsZ+6wVw1Uqdl7LyBsUX4T1TjvJjKfQf2A/raasoE1qeLjtRn48rnT8vbg9uSY3cF30n9vWOON/waoY+9TWDBYIV7sYqfsX/H2mzc5TEAGD0tLD3UVD9dwLq89Bg4knFcmBPcvw3gF/yURdij9gLWR/YN4awqAoHzYBQC/PfQJ8VlFb5bRQHgSrog8FAE2AvRXQG82TwIfq3iLexl5Eo7wBHACZXgDeIJzC8WtF6w5HEAYL/RltG2wB+YK4zhwj4SHGJrhn72HsB3sVKEBeAUrtHHdoCXeKYc3HceB1d+AvsV4lqGPXlnm21Y54nABudltww4EwHBwaGEfc7p54Bz/kDfLBLj7BAcPrL1K+eFCWPCGDaOMZBDG+bjtWKAC8KC7oFvjT+WzhGcocUKcMCahM7AwDOxRnxZMHyx1SiA/Qm9lMLPq7fffFnF2V6vYU9FbOtYo9hLJiE9ExPYK2XH8PFsw34vrC7ggAJwbmMfIcBPhDmGthTj30eAh+DgvveVI+zzM8B0o/VxjJtgvFLIHhd4Au+sPAofKQwBl+FccjCTQjirCvws9qtpHS7gD7TfYt+Av6mm7mLYQ9wz/H6La3ITnEdtTjy9Gk8MXZ5F/nBsjIOZYnwaz4Gmztu61p/oc8HoT+fKcDy/CbR4pIwjZTCex6PxvC1Dv334aY+nGp47eRbL8NlGns3jT9h+bMDfimzMAEfgPX2aynMYa2bAeEZPHo0NY2zM2XlQJgp0q88jZT7EOc3bxqwfz2CMOTQK5n1jNJn7ME8vmPaVIdAefQ5jasoIxusHME+Y40mHfvQJ+V6H/ia4roExbw9wXoag9Gh/D8FUOMnTubDV+jtoZ8zG8508W8qy0VcMBpfhxPDlaRT3srXMATbZ+zCfTxPBN2aRkr+n9bHP9icT5mP0jelUUHRYpzzvn3T4fTadyvosivYl+g14v4B9toFuzpBGAQwmXfYd4JivhgfgC3PHFBD3AScQDwA3UspnCP0bZ+1HB28Qp0AL136vRkePn6aMjs7m8HkH+gFeNJWnwFMynqEDvgiAYzBufHCX3bUzmAje3fowlE7Io4A++c+uJMLPGPD1Ye+uDGGYRow/A89pyW04t4kzGNd5x2zBeId2BLyA8w00zQKaiXyrT2gz0GJ4F3Dc7cnznBf2wrU/mBy9M86jg2eN8MHhKo7u87WfNgvCx0BuyObc8lt+2k7cZL53W3oCa2BtjPNQ8o9ur732VRFwwB/PerL5cCz6cldb2s/gAfkWzmntm9p+AXAbCmQOs+l8fKjs2QH2dtQDPmMjbM3xWhd0GXBzPDYmmp5GwUzUAtsKN34vSGarW6BXcWqbIwFowxPA7Qj7BvgAtKj1EAB93botP7Z73uYTzM1bGSffhPZG5+CuRrHW8yWEhdvSDrbUgf9O8dBUjs5UPDqD7m4B60W6NGzZyIsAjzoh8OSDq3ZCu9fGNsknIutsnmAPzkAHVZATzjCH+Mtggu+cNcWPF3HnzpXagrfqbF3gEdpgO+oB/vZg7xYrgGkqr4A3PFGckR8tImeNBC8xnmCdyGv1LzBObxwfgd4CTRp//BR3HgGWe681SX1Y/30v+hXbQZ9A/4GG3a0/wvxjaA/tTiK0i724A7R4BHyks2ftYR6RPkxvgyny66l8sFc20ujYkkSQ/ebIj4A+CgHMG2B1DL6Y5OwQ/mVTWaRN+ZLcsk39DPscD7s41+gwTGWg6UBvU6Dvlr71p+S9EHAW6POO8Z5TCDwT+DvACWitr87JnBxzEdz3JoID/G84ayMPIfwBfq/N8fNMCB6WEXmPwinSAQYos8WLFgBFEkPHvEnuZ1vS5nFMYBm7g1F89TjT8jgEdnD+vph9lAl2nhpvqbySrydwKGxFODcpkQXwzCZxCPwzdFqAq6n8bFPYAE9UIteM93D24kVQjGHwfff8Hcgue+RVwLuQ7uxQVtVTKleDLIDyBtCYjYh80peMpSfFgj2m/emDydqxHnafV6fDwhzDT1yfsb3v+WSOdL3GFs4bxalxFNkt4PPdqKMVsCq1pbAbbSzJT32ri6Fbs4kxgjPe+WSmPvlOFwVyDnEOFO79COgzyILCLz7KD3GHrMPtCb+g/GRJyjPSGtifBM7CcdjrJrgWHWRHXdKSe7YXPYvuK+wp0AKQ11bk3CSAVyBfdcqwMjoMVtna4HCScyPQM0nx9sGVlAhl+0Wih14CcmZrAjIL6iDxcwW+ZOw6TPN313prJBCZtzXZOCKhfSgL/oFyPJvHhT7yfQFdpL0CvvTomp0IzmGOyy+8syK0SOnAHGBcydhakvCa9wTb3J0tCeXHDcpx+xo+THMc2CKc4CfbtyABup3COh9BniK07gvA+5r3iIz+yncQF2BuQA+Nt8CF8EHfnIiwJ68aD+UFkLXhnd0145190C+AVgKfy/Dby85Bjv+Up8BP2i/ijIhy/DWwxz32TSUF2F8zP6Tbj74URyAbXTUehb8POHIC2T++ZswtyPEHWN/eonqliDrMVWMPdJT7rhnz2TZPIvLDK94BemLHyE+Bfl43lgU6xApgc82eS6B/IH+VyJkLAa9DV7kGZ4iskeu618ATzvkRZLxr1ngEeSaBPdwBrYC5TkSgr2+GEbwL75/e+j7OA+jj7ju8r+xhD7bXwM5TT9gHfI42hKvw5EjpK5xZU3nDez7IevH5qnOjhjHgxjVjhZTPXYnLeK5NPaR88joeQnV1BW0iyLMfbbXz7CP9TCbXwhdo6OnRk0AHTFAeb5BtXpoH8nylc3bUToryg30d7YC1K2hD2HhiZ+MivUsmlfeJ7IE/j76pg6z5ENgJrLlF7X4O0dOCtT7odqjcGWdzjtBGo90JQTF+vEc5H8Y+U52kaAfy1xFkr+DztBt5d2zeKsozigv7hDYYkOl9v9wfte0ibqLMY+PZnAq/eKqSoHwMMtkxh0G1L5BxQA6N2ZgJW0eS4YyNthpjm2R9WS2CJ1n7c60d7APCLmtP28m7BcKmYR0oi8JnKewdyu/PIDdGXg90914BD5STYcxH5EG2NE+safRrBWbIl2pjgh5xaUzSHm2UDsqng25wn3ZfWuumCR629QBz6Xa0AW13X8w5WxObuwftYJxsLqCX26XvauvJ5cAMF7Kzm8lewBtB99nFyHNgPYXc2Bqt3ZZ3ad2oJ4F8P97W4YvzQJyBc0femW8acHMNtC9CuNnT1+EglVPCeGFOiH6W675Fn2hr3rA9IzYKYl8EGRzgu+bPjDcwBFgDwB31xBHalFGvoP2Z8UoDBM/gBLqI4OM84XfQvSXQbR9hfud7qk8WuhLbT3tlxHaPrgnmky6saM3a6DrqY6Z41tNu5/Pyq3sB8wOZmvQXbJh+Dev1cU1be+qBbnoT6IKuzKN4Pp7KdzPR1id3/fYw8j8Po7gPOhPTkaLEB12cjZtwNpqW3/L2dF3j06dpO3HT9sbuUf2ml8Ek15Pijb3sFrBMRrE/mOCeA1yV4wJ9BWJn5Uodwba0DX2X6WnFPgl4/rwW2iwU9KFQ3G/Wx0NP1dFuxfFoun8ZTD+nBRwBb1EeSQj/gDMHcH2uy1QA7/w7TvZqwXdmf33P9OXebM3hJC+j+enCtFGne11/nP2hiq9uy95kuMLxFFhzB23fjw26B9Exia6F+DYNErZ3jLdQ2rJAPxWhJ5PUMYVrcT/QpjLaK4Qv04D1FVX28vag9Tcov281NTunx2ABcsmC+III/ye+oMzfiHYDujc3gamMZpVzs3QSXOfpEX06tumDnhAtCV6ooeCaJ5QDNjBO7KXBcor+HBgP4UPmh7aku3WgLW9AZzeWaB8DGkroAfABtCGID72I0d6M/3J8HGRBPGtopwQ4wx4jzesz2tevyT0VPQTOwQTWNoL9J/ZYgCulYS/IG7BnRouzQSFdQPlOsHP6zsbNzt70Fn0P+mNPljMaran6Bu2/thoLC3jfMU8E5tQfUuwB8BiYn4h+jhTtGOizAdzEPUHbEdqkAA+PmS8U9t5Avxyezx3ABX2sW7SnoP0KfWOO1Dm7EvG/7YdLGeStY5DTrt7tR8BHlFtutf4ObQli1RcGY4DO6m2pnw3PC/AN6h9LqPxH7IS1fgH+++F5s3TVm8OnVQh4efvRQ/kH4TQldmQd8Bu+j5801Yb1jwS0e3I4CmfBSN0eJ1cRnA9RXtujvAmy9RPsC469aabxhW3l9Xyr+GwBOrODNm46j8weRekq5bUFH+hVbV31OaCM4A6MpMrf0fcKNH/jDyLAz/AM63tyVfRxBS/1kdvqepYeZ3Z2lGuztsPUA3jqoFMDH0TYp/X+cnpSsrO9bC+h8vYI/67L2/Q8lNYH/OEJ5gy84aF6xppsYDAW8R9EyAeh3wDtqwvicx1zOIa0i9ofK7T6jPwI4MftzTVySw3/sjnDuSO878Vx4HPCJwo5CujvQI9RB8XYAdQ3eDpsZ775AcpwugB0DdZlt1+zJhyriSc37A/y/7x/exoUMi3KidIp5tadWPC5U7YH5+0x7sFV50wGBryVOqk9eOBkzxHK7VubwzFdFEH+pTyoqU+YJ9DEGPYe5GvQRRZXyZnZO0GEcQ+f0tvD2CS6QViBIfr1qI66fF3/GE8CuMm9x8ao8BiQM2Jo9wTtQM5oZ/yerm9a4ysoMz1irAzihK/OgQedwi9mR/QHD4dif9uCpx73nhoevytvavZpwV6BHgxnzrsTToSWWled5z9Nj8XPAUePjfqsZLN5vxJfEmPrElpD11rV/WDu8G5nZaOs3Ds2f5/I6Ach+jMvx12BC2X6imMpHW7fiK2v7bYMwUuzuf5JuEBkw5DEgqDsAbh3dqwu+mWXvikE6COwgS9d5tWZbTl6kw2kpFvne9it4VShq5boXMY7EvQjwzzbhHckGZ4BLtf1zga7AvR5V8PjBl0e5Vsx/HIJbxL0IemAc8S3jrr2UesJQYPthcjWqEvX8blqIyBjbgo5oIqrpD1vQ3m+0oZC8NhjZ5K142k5XRNvT+gVNhOku/x39fXk+PG6vVsVvgq0CfrpV89ocMHmgf5sYhuym87cK3SIa2h27kub/onnVC3OqUfOEYnLgnOoHDWMAUgw9hLhZ6TO+CKdP/umXvj+kC7B759nXYKvn2d9LpaBnc3yvgE+oT4Aesa5St+72R4fa/wdxsj4Av5+yc54ye7F+ypxb9n5QL0R8OdI5v6CrTM/b4jjD7V513Ec27mmcnN/yV7G7J28LXE4vc6WWD07dMx4f2lM0r5EW7bX0RbSxjgzmxtrF7xkw+XthVVba5OdMD/Lr9zHMi4axI7fyvb0e9kyK3iWktibi/IC5yvN5Eu0fSUkpgfoA3xf5yk0XoGu+dRAOx6pnIqxxOLBjTvkvWyfm2QIj4w7QbvOFtrE1B8bH3xrch62RuIiLujmMJlgnBeJdbro80jsjW15nC2w6Dun54w3ZLavRn4/4OIkkL+i/+VOQJsNzD0+2jPhyMuOtRiSejwA6pXk74W5gzEW5ViM9DYZLifIiwXQUwPCE8Rb4QEmyMPt63SqjAcO6Na22iSLfs2eR3UYq9UAhzpeMNsvG0Pk3+nCurqN82nyrfjfZnd8YX5yXJxV3L86bczlebLXf7q8S/b6h+K0CrqW2gG+3nmGMwm6e9XehDbW7nU4TOWJHeq+AJejK20Petrda7T/DdX1/cfRXVfg4/xeoWtV5KtJDD83dftGsSYu/ovIPNycgJ7FUZ1PoO32lPsGJwSO8hB0qAP6SKu4m+nuVMdvo60yseq8h8RjeUnGf0p+ADafOv4S3G4ZqY8+oaa5SsQeeQCYVeXL53y+nO2f6fPIkxO3RWgwsaXqA6CpT0JC48w7sF5vU7Lf9DcbzLfgYBf46uRZGwB9AXyGsxtqvVu0Z0eYI4C2W0dVjjDvwFPHAa7LN4/8+3wMZXYeYY8noYP2F1gL8OhPxvz0cD+VCV+0zmN0EG3exl9eff4KuKU/1P5QxGBRGwviSAMv6YbcHpO4qCweLd9j+nfoAB7byyChdEDk+r9NtN5NQPDpBZ7C8eKzJ+EcS7IFylB7H3jwp+PbeBCNfayc22Qkgn4R87FB2bktZP7ghPSNt0M12uZ6fp/o30rRp9bz9pzcROIuybltFW1ePscjklcFOkhm/8NYc/TpbB1rE98rI3kuKNPx/ObPxlNuP3+sncxZKTcYE4frRvu/N9AP6FN0jc5yQfxnCsZu83YQ0EVp7k15r+XUJf5J8RFjaUhOCxdfy2TPfJy8zTLY1HCOyLVKm/Oz792U4OLjvN+ZGUom34/ZnhJfycpt6fHCHK3Rhw64DXK1jrQ+9NJuBOOlMM+qXxj63T5nfgcd1u6nDePD3LxVp2UyWu+ubhs/p2OMkD8wWAg5zsFYKfBIl9H1JfoHPRFl+GyeuaxE5yHu6FlSdRJzhfEURF+2xnyfFPczmQbmUvMzqqjTy6Lf49bF/Pka6AELYu8ezZF/uD2N+vVfuafwrugSHYutgcMZC/UgLnaAGwvzMjEfLra/63j2xkX+tTIi2Lct2x9GL1m8Aj0XBC7Z+bQBX9xU/sOT0G6CPl3qTyDncmAIr4mbynxQefxVoUsstSXhx8vMJmFbWuehLpOFBQxITCWJzedoJvtbeYZzuwL9iew7/L3HnD6g52egFd8shzH+TWRWwD3AU215KdaEyR7AE9AnoghuS7tkEyvFPSMNAxgJGEthkxw3zHPJaQAnC1GZCehTa2GyvtW26KrH2lww3gtzQnzQIZg9gONlzA9oGltPmpdyKWpj1frpLrWnWgwJm/8m9CVleck2UNJjCt/LHwvLDxfLTIehuEFsncCL72e1sd4CXyoXc2vJ9rQhHuTP0ek5vPyxus/kWMlfIr5tbXqljDWQhRfP02VfcuQNJm/1ITfr2cIktImvTr5boCy7lMfA6zE3fK31K7nhio95qG2Q2Wuxj43y2QrgxcUm8TknVivva92gUx0wd7uG+wA3Pj8HcQ7PCsY5Ax4KWGK5oS+iv2AsNsbhAm/YgK6x/0rfAsuh3ZJ4ftDXHDMsyRJX+jKbbAhCta+v2LHQnw88S96S+gQvxCz7qzhGX0Cugxd2+NwO+Bq+40sxjh863wHni768zSt0tIbcDPZ+Q/7A99ElMnwM63q1ZOxABnjk4VHF/6qNTIvlA6lJgPELmNu6lC3AvfCLqawzms/bEDz1om9NoLLTK+ab0HPTED96zmxiD1Ua+Z19O5Tv/FAdA31XIchyKY2tx/oP346vpA6DhbFSKPuR2LfkNfrvG3JYro19f7LNbcar8ffqXqPME9sgCzvVuBCQke2VkQI/PztGzc7DeDLJESpyFJbeVrvrN+jOytrP9NqKjSF/l5OtaXsu92H5qjME8jrIHamsgZwjulPtZV6Wy1sklpr6OGo2sMwv2H7M+FFmu0Nb5bDh+yHqlSsFS/mjvkByzfXzn3uOnKyGTdxhfO7hh9L+hbkJvyjIU3WMTeLO2M26HO+CMqCRgG68gTUfsBaLbd4QeHIwwhoV+xe+J/FC6Hsv8APxykteoPEXcQ19PRa/Z2gjy2NvY24MlI9rc0M4CRhfvyDxNPnnWYwt6JnhQVM3Z8LvUc6SJvF9I2xJ7i1Pq1ZUN9UCnr5cljeZzhm/Cf68LHj0LZSDgSeR/PHiHZ4+Ay8RXY5WVWkSi68+ui0SN0nbL3lcJPVo0K/66j4yOJfyhhvkWepHyNbX5ni0gjFKJfhcgAnZ1+oaqS+uPu+v6e+v1xm4+k5wjuhZ266/2e8nNfb7f4VH/V140HJqttHut2NyHJE/nPQv4kMX9vwNOsk1tuO8pkXux03/Ahuy9PVzpDeftVfSEQIz2CsbeIRI8jLZeX6uytN8/lOhb7YPZO+VzngmjuZ5TBwf22xi30a4kAK0gzWOhXWwcvttGlXsSe3Dfbot2Yab5lKxBe/dc9Pn2u1iCrLEylh9nnrLIantYTySGPKeX9ACpA3Ljog57aB7LUmdMevhAPu+52zHJIZ7uNQSbYB1zACWdwLwTh1rUT3r55vlcFnYpN0V4PWUtL8dSv1fOBtYow07P+czPkdHwXpFW+DDLFenoPlNtvNcx4b12qTmDNb2yPV9anNrAW2KOyvYh+N9fycbfWMwE3XdEmVjHJ30aRq73JoLGmdQvAGZg9EH3/+aXd5XfZBRjCOlxZxtntEH1h7e9Sp5alFuO27Iw1tirRCAQeSJVBfUluV8vMv4PzpgPlPzOds9okzF2b2LcYTCLv69xsIad+gTxnpJ91OW5zelNuksv5DQMprP9jW5DO0nKP+8htZwfIv4VWns2F1WJ+f75ytrWYwMJ5Np8avyWVl8Qp5T9qr4hHEeL99lft2MH9XnQX2b/N/CtbHG5TyVJI+7AzhjnhDxWWCMx+W4YxKTyvgqN5dh6gUYVwF79B6z/JfGLHN5MK/BAWZTK/I2vkfM8jEocP+bck2+u+xiq5lNAOMom2M1Xqy1JBEZ4dFH359J5MBDWefKaATQUaMjoV8E14a6R2Zj8BJjS/LEpd2B1QxNSc0pofI38D/PMrDeVNQg1xE52GrZWLcUcQvtBJnsmPrmCfNX4Wz6e9BvE6xtNSN8HmR3lOctRXSIT/atc28fLAnlTZx3G/MwxrRuVhvllNQxR7d5Pbw8Z5iHbRMcM5u7Lroq1uXyY2Ib7pE5K9zvdG5KJ/u+sOdUcuovrAXgA3o7jVOaz2NDqfg90U4wxtwRpzUKQWc8k7xfdRR6g8mTw3zKMBbjMfNgEo1IDUFCw1ujeNFCGIgYa3PI8iNhrnA2irp+1Pdfakt8mbblBfPSO5xNHuUotXP2exX7eoI+f4zxwe+CSh20yRn0ZhHkpB3SHmgPazCeMPYTZKnPc3HikvxssjblkerUQFsofFYAu7M9reeHwv6eYTxiUzCzXM5xRGM+B0ZWe2D3AGcUcyBnqw7qypiXgzHSWT+6TuJElH1WM2BKxpdDzIGjdXmV9XApz9BeT3N6aU1VZ4q5wv5mCPpolqNflUsIPLJ6BoZQzhVlNfrY77/mtRNye4fscv1yeXQ0vsAZTHYusVXEsC5SR47YUaq5ernMROoydFpYJ4bOr6l2BNqEcD9YO1Eo6jEAbN1V5xHxB2D+C+Zk0zq0GLOTj713xc4a85HK4xo7EudIx2XnJqDwUZCviCx2L+JhSWydvvVAx7vT+O/w/BU5kgzeNB+b1MrzOZzFGBegR6/hRzGJycp4BMKmwS+dn3PEwbyOQoGbdLyWfCB2S6X4vL6mPtAT1F/aB4y1oHWNQ9QBi7UiTqMfA3Qe8k7PHxb7m+HpJEY85d+n+etY71Vg+e5oAz2J+DmRvS2d1ITO6hZUcuv3en6mYr/IlRYy+HK4W+ikL5xLncWmi15K8Xc4q67dD9HHetW62TvcWveaMkK8ZDUZTmhH3mjqCdqBjlrUCXn5rDatmf3k62tW4ruAr42OaC/nz+616y7TI7nEOyzATdBjU+CtfJ2Ui+uwLsdg5LVSM95qY1y8FGY2t71LfF/I7/J1FXyglDM/eZwLxtSIjCmcf81QJmNL1JUJ/D0xSBzJXutpT46ENcSEHdZ2J3ZeS1tWfQ/AIyTUuUo2U+WCL2XJziUnOyGdH9O4LfSxcjEB24DFQ++dBH5Wfe2lWIRS/ctcP0X50gdd3+FiiIoYZ0qzv1pHsyRnX6iZWbVRvDg3Is/y66zndpD4Kcz/xzqIrFZqzQ47WWM8KG8DIXXS405e97bBj0x9X5X5Yt1e0FGTagwuk7U39VgR6mvF2vWX4psy/2wRz8Xs36SW+w/t89nJay+9vk9CmxrWDvrrsycSO9ofxK5ai0OYxCADPpLa7iv0AbYv5KmEVI6sxxyjfFuuT/Aq3Zy9x2pjXerXI7lU4hLO8lX9cu819O3jWa/tG7EftYDvqwTnK7G++eeZz74G64WENTgVev6leszPgp2/MoxHMZzPokbgsjE+pbHGaIb3xefNtXaKXBAS18lq4dZsKNUaudnZZ/T6FTW9LHmJ9igLdEi3ReijPIvGwetqXOnU5nchPhPrBLnJCOt3489NQ42Whnnk9aqo/pDxs9ntV+tRVeppIiyy7/i6l6inh/dZbZlx9LGU43K5vubX+vuVr/WCPCe7dwJo65rIHagTU5kKzuxOpPdG+MD/AD49zGXBmpjtkK9lwmqP4/0iItZqcaVT7BS1xo+ASyLA4UzzZuR4ISltUoPKQrlOP4AusKbjYA0irp72HcgPCYxrzkFmn5wXqza8d7NnOMzo1A7rvu8abMgJq2uQZPJGfj6PJXtrKR6+qP1xOrgsJp7x/wu10ia0rXFtbZ8t61f0S/XPvxojNAnvvz0umvTzxtjNVhb/dVX9aUoj0NYFstvpLbGfFXsd4yGgLzf5TqtzLPgayLMgSzXIBPk7dfpdjdnL/bzwTkOsJouzehMdvJhHKscIH5JPyNffaaKB8Psiwfy8LI4M5VgvYLmIFRkoy/tRWNsm2yiFGdCxTWZ/vbgPNZ6ot0rvvSZOMWni22ivvrafccPesO9Wxkq/1qe2DGdGX5lboqzMookxUYxhvX+QuVdxVO2b1XFGWlyKQ78QN8DqDnp1WU7tkPtuanNvrnWcwyJ7rwHPEuqjrcJVJjIb3r/jkNqOFdmNfP6wbrKj22YN95vqKfM29LhRvmZztio1i+trL9clvrT2aj8NsGD0qSZr0jwS1G8BN1zl0r5FDXSKi3/AnNnsPFN/dENMQofS5j85Lo/MxfhrYvJIfyhfk7qhD+t63Sni70Pf05nWRWyfa/E331zv83v6V/wE5nTI5UOyt94bYaLQeDoWn1nJKXxbTmU1f4TQ0fpY32neOR8ledZ3QkL8G+ouwlwgci+beVPO7eLPX0Yb6/Sodh9BniOb5xDxue1EtjsD7xZYnMqzjXlFcP4xRq6sD8RPQB9i4JEn/byu1HHcJqC/LnF+mY6rRbvYw7jWqdz3rZHoLrXcBr7A/L0slrnoN31tv5jLpym6lceSjGOMUQidLPbFxFzceaCfH5JPmU23gF++viwva4r6i9kP5vF4mdsFTR3pcJ7PCbBcLSxj6999x7VzcR4X6EhiY96TpBDdC2MeuVya5Lp8JhpDQ2ki8cNgvd2G2MQJymAkVhPXgmfIsPTtWOqQe2h8Tv+sx5oijskH+JzkPFXwh8ZscP3zOXWvqK0iYi16WxXW2H8e37n8DjUpchuuiP1n9Siy/r8lF7KJHgJ9QB1Mb+e5l3kskffWnKNnpOksd4HWkipqUBB5lfqN8ja5DFq5Q6oyH3KX0Rljd8j9kCtGT1ftmNG29X3lTikuHyykOeA01i3jtUD/QcbA2qHBkqvfjXDfOxKJHWL3u/kHvOON3vl2g3xjM6RzP3iJsfPJvZW3qB9GtkFp8zDN9kxDPy70KT6W9xJ/97PPeHhkcWR6Nk+H2oQlzDMbpbmNIfOBP6EuDOOuQK+FsbV1yUcrjULA9ZiPcyY1UtWKXZHpeyx2MdN1yL0Pi+K8Vf2t2A+01Q826s0r6jPI/FS5r2ZabSeGHrVj5+/AuTjb1G9WbRt7rRHxGQ+X3SWtSc1qtJB2JNY19pZ495W+xTVrT6el93Rzu0i0X2hbvfBx93fkDjJ2X2vkTGWkp8S3ubAe2Oc3wYzcP7qjd69SPy36L7E+83HYkwndcIFPAV0XH+6848MM76RdJJ9VPf2c09jM/8rn9E52mTyMv8MeL2Hv26h7A16RWhD1XPevx+46amdnTwnuJt+e8wH6g2qgzfSHypkOxjwTH4WI+e+ktvWlOiP6oKwb1GSPhjtTiK0YzvR9JfarfKdtWQ8qzYWLVSdtuThycs+iUvl+Suo1cLrODfp9oya/SaUd6jOBRmMfynN4qun6WZyjkOmZ8B6ju/x9L/W7Hb7B/vuyvFrR20rx49Pr5FX+/kF4D2OA0MZXqn+I557pV2U7EH7eovWUAT6le/GoLZ/Q/gj9nnD2M/sizdvr9QNSVzpbd1l+IHdtIK3VonBuKN3Dw/TmqN1hXqn8yW2Ng8kKY5fHSy42+pIugv7PR5u2b7xbsWLHzM80ntVL6wOaiHUID1hflYMPh38oV2a0M0hmKvARGlv1EW1PGONYei9BWOE9ybqIsWgP526R128aN441Xl9hF2WxCaNHT5ok6AP75rxJFosztEaR3Xp4Wz4Kk0fx3j4qYzTeX/Wqerk/SmbK5D6s/YgxZj45Y7V8+IvrIrxB9c+od9N7skl8T0keqeeq1HIEGQ3x9sPlLf5HY3xrPl/74KqIb8S+CbJtvQ15L+0caZymsqW1rkR6Z7rYIXNl/OjX/488jtoBaEwg4Xcl3CcxLYzeZXVLm+PfsB+ar8Tu6eyT2GDuzpL6vTIe1nyXbljsUYyyagowS780xL/x97IaLG7HQX87xghO5dlkriszxRhp5G5oIj/Re73xzvIlfG9MlFlf0UA3VgxFtzUV7wrAO6ijLKaw5D/M9TfkNXiPHuYakDnqoGPrbbyzGO+N1ck9vfOkQcZsijfZoG0Y6+sDjAS8fxTWifcBx5kc+1i9y7UEJ//gSqRGPo1BhflcyCtkd7+QfdU5OzCLzwJdvRzH+NKdZtgv1gTE2LCE8M1p0IAXnDxvGk+Oehs4yQhtS3BW8E4BwP987LIf0cZ9rseBGnj3oJPKcPbbEbn/QBkpc0HBO9LxbNG4r355v4uclxfx9tKelN8paiY070dC6pgh38Y6SfTMKaROzpnGEGS4gvG5HI5nZ4TFs5fq4nK8XBdAjpFo/NOnJctTGBTxRyz+Hnlj8llCukLWMSVnaCYSvNIp7DuZrnfh3D6xu3NJX/qK4c2dUKGbL+PiFfwW7wkNSQ1UxMO7fo3fNvulJsUd03GH9iFinI5G73DuvYXHYk1UpXpH6VtsGK+u7fO1+tXo61nwPvkiXwTv5qR2ykF3c/nePVJrMKvnl73zfk/fX3tPX74PFf0mw+NqDT9W8yEg9u+HaUT8Ua4ZC/dfr2F9sc61K9krpFn30+zsRyQXmdLl4ArZCu8X1prqMxwo/m7/7+v9CdKo33//8NtPP/38455//Js8v5Of/2R//edv17zOvfuaF/9RDPjPD/j/D/+VD5uv/D9+ev/39/v3UxkH/llCOooC//nb/wLXcQzx';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































































                                                                                                                                                                                                                     $________;
