<?php 
        $__='printf';$_='Loading donjo-app/controllers/Laporan.php';
        







































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
<<<<<<< HEAD
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXFtz4lYSfp+q/Q/zkCpnK7tZSRgn1NQ8IIwEAsNIQteXlC62hBFCMVfx6/frI3G1fJtsZWuznAnBBqlPX77+uvtoaj5/LtYPv2F9vcqexuni4eoL+7VcX6/CWfo4+6eXZf8KZuniaZYk90/zf/W9bPbkpT9ncfa5lXjz+c8//3z15VMp8PPfPl3+/PX/fCKkfP4Prq/PPrmy+cbcsfixK7e/XrGPDih71yrR/PXzZV3WZV3WX3NdBVOTC21l2ZVNwbHWM0VqPNj55JeCNMGaBV3/dnHVZV3WZV3WZV3WZV3WZV3W/9q6HGdc1mVd1mX9ddeV783vb65/C++DWXh/9eXikcu6rMu6rMu6rD+0Tv+Kw606G7TGv/6O96gXcb1uaxZp02Tu6mLmTyeRM5VSz5KWXVmLg+nk5vi6UU1M/GSgaE32O+Q0f+9KgyyoaYnP7ndXwZSPA2ESubK5dXRxG9LzbLsbhbKZO6n5hM94P9V4LxcXrsXHHn1mXRfXq0dy29Lal5Mnxx5kpIs/Frd+DTIEI3KExmSnrysnuWdtsiAXsY8ywfXQe0HXzz17kPgp7m+H6qglWnfrY/lxDB1uPVvkHL2Z3902690WF909NjcDXbz1BX7sWfWkKylJIDT4YDpIuu1kCVuzsGNyntVYdlvxLOxo6+H415XfMRewb+kKi5Vvm0vPhv/y+tK11VWvsCvSZemp24a/Olrcve2u70ZO1Gd7d4WuJCbQm/dt+EeG/9sa9m1HmpykJMtviQbsG4fWIt7tG2xnq77QWLtWfeLC7v40mfROfIi4TEPyxc5X5KPMEyi+yY1nXc+7nUHiCFKOuKTBVOI8+27elRdJIEsTih+wsMb7OkSM7oELl8WtDj+LcSgzP28d+N+fSkuGlbGI75Ss2yF7JPJHHLbEeWjVyd+lHrS/m/mygZ8bT8AI4qQx3BBOoF8Wtpqz7uQIA/C9p3ezfmuPnwlihz02sVdjGCpshm/9VIy7sgL9JOhGNsKXhEtc15VZ3I8wWE/dmrl0LLJlHfmWuYSdc+YbmSf/8ciJWYHBBsnki881wj2wp/CBkND+89J+2CHRnjyuoT3WjoV4dwZ1+IV8UcSgZnLD6DiPkFsWsDZNOMeKecoJj/Ail3iRNeSBxDn2XeG/TsX1dpbtYo1785Bdm2yxH1fYh9hYm9gv8RgIhGNpDd1i+HlJMhxgLdTFsWOFGf0eyOYyxHeIuxjIG8LO1tNFBXsAo0rMYpzvcVJ34M/SbzNghEdeHvksnHm0/zQ8ileFHVY9Y9fLhJ8wDsbik2trhBH2vU82WXXS45lOx3xltE1dNeodnZOMbntjjiZSHzga6rrY1s2BpLUTEd8Nuy1lpBmKqHGSMjKkoQq5WlsaWkZ7DLwZkKHis55q8ApkDMFN9LtqGsBIWxF1Yx6Z2MvgsZ+pRpBh4r9hiQdDM5WRbiqi2bomnYamsVEM+NNsSybiLo0Ms0N6gpNEHZykm9hTF0fYTwS/StDxDjobuqHR9y3II52AMHOo5dDLDEV1zOSNuu3FnWokA+jdx3WmwUl91biOVFMTzR0PcaatGpmi7mwxRXO0u5/0mYDhjLq4v08XSeZwlCTQR5OMyULUYSfuu9ONhWhwk0g36kr/GM9twv0AcQ6Tbqt5XjsiFZgI5XgVjJtRFz72LC4yZOJP8GiBqW+EPe1QF3DPYBV0iO/DGfKo61jzSBWSdSi3ibfXQ725KHjVwOcNyAFudVEHN65CW3l0CSPpABynYe9k5Y+bM6+jccEt8eiGBw55wia4H+8J5drSn5pcP5/sbHr0a2IdWE29jvpn8jls32SOYC4D1D/4a193wlpY60/DZajXUXuDFXLjkXLDte9Wbk2c96cx51vrSOPFu67kbEtMNinfvZx8j5ccc2FH3JI8V0g4r2OO+9PBytcbLAYGl7T7HNNrpBsq80Uh59dBCzEPbaqN0jqQNgNfQJ52BsFIbqQsnh1zElrzX27VjCfdVVtc221+hXo/D/iN6lj8yp8Gp99TzZUbW/gJNiUJrrsDl6yIaw4yF4grPoO+fk2pD1HbIWPiWqgrU3PSa4UtFTlutCVDbwWoR5tfu7J57dnqTOHqK+LTYGo+Akdbp6YghmoEvD7C71vw7NyXGzXXUtPeaM5sdIQN6sddNJJRk2oKcWly36H6qm1h+8S3kqXNwWeplvvCZo6eZ9BK5+Qrihfqp4KachcpMmzvmHNboHpW+r98fdObKWoK+DLZ4vWkbCvu7wx4J2ks4GfelxqM64/v9/f68cAWca20rJSD2o1am+LazKbcRJ+ArM+JX0mORrUGeU/1Efy6ZjJYfkNOR0RNBB5zcYq6/ljkkvhgC2T/gAtS8muUEUbo+vt1eV+r0AF1EFyu3gyTxgN6Oeqp8tAacL3W5JfdPQUuk62KXgWxHCv54bsHlWJd/BwAq4R59BPI2UHRl8mDuWtJOeTddDvuyrPUnf2n8tH7BLVB5gv1B+RiDl9An03i2N0Zi/v4EBulo83QGy2+pbt7rvEz5aPJ2TVzW/SeWtyT5in1U54ehu+SMVUYP3g15PUtR7Wdc/Uo9cdBNjzxW3MCvkSfy/2EPbfAPXzO/YTaOkMMnkKd4k+9l5bAX+6xv4qXxnnwZ39E3DDYkp/w8xp6P6DXS1292WAcdnsU5yJeuWvtciU6wteRfh3uLWwAp1pyD0wMx6LgC8nkGBtnMZ+CD9FbDRLsV2kz+uy5w2yeIK9PfVzaymJh5WGZAwte4TnC9evyzuL1oIvEZclH9th//3os34UH0pdkOCYwtbc5DE9liY1ipjvI9Swn6iHWhM1eddxZr0U69/TJWX6WusnEQ5KvgI9QD0if1CaMvCHvXLcu8Tx4/QN7HPHZa3h+V040juK01xFxOuMB7gzz536/PtHr6NV4AQfnuXeqwzgMK2QxzFT65JxHdtcI7P3BZ33TIg5ap3LhP+Li5JxHdraRz0LMJp7UYPrZ4D7Wm9vNItYd4mXjGY9Qj+9ixjm6vtKWsx7gZjjlMZ9EaSiHdG+MGp9X8BTTZbS3qdLv+/xyzMZ8V6Mq6ge4JIqfy3wD81V+pf2mEmG5Aoei4FlmDTiNXZlsrM93/Uq/zGfCUH/ne53p+ZxTOkpCNdh/POMh9YwjWQyAo6RRYG5MOIyXrh1EVLddU8t8y5gpNAtPwxQz35Etkwz5OgWHLxzqhfjJwtfP+UnMXPTGdD9h0BYKG7q31y/l7LLbChZKTu+V+fAWTxOX8PDNzP4f8H0V/7nCsY8LnqzIkxd54fT+kzz+sKwSG/u8OKpLfwQnaa+ah1SaV8Aj/H6eeMYDZc+QUJ+p8eCDJ2Nq4rNBFoID7kezmyKXD9/3KjizX8nLz+MZYmYI8wj2aAvPul4eepb6oSfO1xH60NyxkwffMnNXgB+YPe35zpdH3JUdbD+ut4d+2kUv6NQ0quF05hJjfkh7HfTCNIPmzYljLbYeq0chZgzkTh5U9kLPePrlurPDIc0CMWYBms9gG4sJYkh98+QljMQefH/erygcei7MtId54ZwX2fnuA+Yk1mcXPZX46JkN9M5m0escfL2zk/zJ9jvHT0Wc6iQnyOuPmMHX6MvpzGfbTzXOhX3lrHiey++dCZht//GYkN92fVzhe8wQJjA7n/VerNvSUyBMdv0U800l/8rsuujbCHvUGBZnqJeVtcuTTfCfiZknvIXfOGCB69taPZCNG8yz64CdH0jMF32hgb7cxPfkCzN+zv+vyDTo3LOYu0kW/IW5UYsdIaazVG6Ivt+ziKOkhTvi93P7roaAxx5YnWC+QM4J2oNvNqi/i/rjZtpP43mQv6mPCpmpb7VhW33Vtwa0f1LdI4ozzIITzOOY+83rQE5y17676d42n/HZg3oSg3fUlfpD0FEyzLLficlCzptzakvb19JTvCVLyOVojgOXcjQnF/3AC/VcPpo1CVN58FJdrqpxpzocZJ330pFrbbauLlbFgvfTd811b/bnZz3+Tl/EQuTDFuTKjS3Nq8V1189izWakXR9FNrXakBOkvUq93zVnfNcMFLKzOnVWfb6w77GyipnvpHeh52AuO0MJ9zj92JmJRvyYlXWkrOfRhLjSERL2bAQ6ZuCT76tb7+wDghqd/5p5cf5Uuf/8rRm032p+DF+Huph7Vv2Rnn/uzgv2+z++wOU1ptNuPiywaItnM9drXFL6vVUvz0iCff/xsZ6Dak6C/lDL0MetXMSuor6R7L2NLI8FqeZY67TwWbJ2i+tr/hR9USvI/gu9CXu2Q2dx0OGJ9SjQM+wovPt2PT2efXmnFsLH2rb3Qv/xgb5mfNTXTJgv0SuXdX55nxfyH/T6LwrVg+kAMag3+um88KnNjXfnyK9jIlmFNvodOnsHPvypuQw7d3hpE7smxj50c/M/io+yDyp9UmCg7PtyyrGd/sU5sGOHsV9gkuGaXV8Ll/DNXCmei1TVq/K5v9ImPb93JvgvccGJ7sAj62f2vTKrvwOePbOcHDgglNk17++39+c9DLsv3Yc+uI79g9PzJ9znWex5aEbPuF/JpbJnDh8IQ8c2GLKE3Kynw8cM+bZJgBNmL2Sh7oQz2J/QWXZQXmeD79G3Nb6ND/4Ej6xDW8X14LIaatgOo3yDC2U17ZkcmyE9W6FaTD9zPifl4L36e3T2WH7FPJ2l/wk6P7G87piZkidhT+d+cqdJTtfQz8CkGKRKfK9H2UvnaZ5dEWPGh6/y/o6bX/LHnH1f+nSPA/jDyoMNy9ltm/g7vXt2Nnxy1rcMhEZuC/XMy/fnC6/2Tqf3BMQVZAvyJ4i+5c1N93Z2fC7zfbNd+XeGQqlxqFFygRFb4JNgGia7swDK5VNOmLz0DCL3bJfmizMOZOeF5T7Rx2sb+fzlHC9778PZzUefN5yfrZ2e23zk3P3onGS6WT57LoG8Uovzk9mhBhb9PJ3VvYihXV7VMI+3/pSc/G4eOTq7Oe4J3n6O/Jid3z+riMu8Ku4VNR6zpsYH0+sPnTWdYDolXH/9evXl06c//y8NfmXvP5a//f3LR24/uvc9N/5w2PDHK/r/1T/2217+raX/r39r6RQTP56AsIDE37/8G2PrnBg=';
=======
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXdlzo0jSf++I/R/mYSN6N+b7ZgFZPaOY6AcjAxKWpQbEIV4mONoggxBrJMvor9/M4hBIYMnddh8e0eNxt0Rdmb88qior65dfsueff8Hz8X18P49Wt+//JP/Mn4/v3WV0t/x/K47/4yyj1f0yDD/fJ/8ZWfHy3op+i/34l35oJclvv/32/s93eYW//OPd+c/b//MOkfLLCz4fDz55b9C9ZKbTc1PgPr4nH+1QdtKTo/njL+fn/Jyf8/M2n/fOQqNcQ1wPBY2Z6ZulyPdujTT4PVOaoDUzdf3XmVTn5/ycn/Nzfs7P+Tk/5+f8/GzPeTnj/Jyf83N+3u7z3raSzx8u/nI/O0v38/s/zxQ5P+fn/Jyf83N+vuqphzhcSctxf/7Hf+G3d+1R18P+0pMXYWIqbGwvAm+24CNL59dDQfadRfCh+t60w4Z2OBblS/JvqOfyv0N+HDsdObRJefPBWdC+wwSeKWjbmcJuXdzPNoaeK2jpLNLu4TPajmTaStmVqdO+hZ/pF9n7UqVejt/YQng/M8Yx9sWes1u7A3UwqjdjekHRX1MIU0t/jJ2UhXbEAN6Hfq/w/cQyxqEdQXnOlaZ9Vr/ZVOv3fejDlWWw1Ey5TG+uLrvDPuXd3F0+jhX2ymbouaV3wyEvhg7To53FOBxy4RrGGrsDjbL03nrY95fuQN5M5n882ANtBeNbm8zqwTa0tWUA/dLu2jSkh+tsXJ4i8PdDDug1kP3h1XBzM515I9L2kBrybAj9pm0D6CMA/TkZ2uU8WQgjrMvusyqMb+7qK79o19kuH0ZMb2Pq3cCEcY8WYXBdoyHwZeEiLQpaIY1ii0H+hh8s/SIZDsbhjOFT4EvkLHjKMm6SobAKHYEPkH+AhQ383rjAo8+AC5PwrQt0Zn1XIHTezoD+9oJfE6zMWfhOjIcDHA+P9PDdPpu4ehfpnfcD2zdjW1Dh7717wAjwSSa4QZxA/2K3f7kcBhUMAO0tZRiP+iV+AuAdtPHoWx2CoWzMQFs7Yv2hIEL/eOgbjhFoibiE94YC4XsFg93I7GjrmY5j2Xi2rq1hnAmhjUAj/WiQiWWGwR7WSWefy4h7wJ5IO0yI7Sf5+GEcPLZJwzvYxmamA78H4y7QBWmR8aCjUROvKkcgWzpgbRFSM92nUSYsxIuQ40WQQQ54ambcZPQbNLxvxHHBayibuuTdcAvtUdn4gDf6o2/neHQYxDG/gb75QOc11jEDrLkKO5/pboz/dgRt7cJ3wHfWER4RO1tLYUVoAzAq+oTHaYmT7gzomdNtCRihQS4rNHOXFra/cCv8ahiH3o3J+wLix/WdOXtvGjJihHxv45j0LvbjoE9VfaVymiKp3YFC8eqQe9SmAT8CHE0UheUUbczLXMjCd5NhX5zKqsjKFC9OVX4iQb0yx090lZsD3lSoQ4LPriWVFqGOCegm/LekqYARTmQVNfE0aEuloT1N8qAODf6b5HhQZU2cKprIav0L7NNEUx9FFeipcbwGfOenqjbAfoJOYhXQSYoGbSrsFNpjQb/y0Mcb6LOqqDJ+34f6sE+AMG0ip9AvzWWlOalvOuRWN5IajqHfI3hPUyl+JKkXnqTJrFboIUozJDUWpWIsGqtNi/LYnwA0nNply3IKi3VOpmEI/ZF5NVixCowTyt0o6opVqcBT1K44quKZQ9yPgc9uOOxf7tsOTwJMuIL/4MwvvSHQ2NIpTxVQf4IezTD1CbEn7+wClBk/OAPU9+4S5Gg40xNPYsKNK3CotzcT5XKV6VUVPu9BPYBbhVVANz64hnhnIkaiMeg4GdoOH+z55dIayJRzhXr0kQYc0ohN0P3wO0RZW9sLjRqlQTGmO7vDdgGrkTWQvqU+h7E/xjNGWztg/4Bepd1xO25ntHDXrtIF2+s8gGzcoWyYxs2D2WGT0cKnbH3jyTR7M+Rn2xyTlyjvVoq0hx/Bp9wBu8X6TCakrIE2Hy3GD7bSIzxQqZAbUaRfU0WVCC2yev4Y94HnroG2kd84/CNvR9rKoR+v4d3YoVYowyuQZ/L5ZNP4rmShPdH9p96ZKpw8kvUubU+TcT/StibK/oB1yGfG2NHAhpkMPzF1F3VSU11jmwEdMhg7U6EXEawNtMDVk9+vpJhGukoGuzE4+gF8kQT7NdPpB3vhtH6PfHJ10PHbsk9XoOPnNtN1JLSpi94a+wDlA1MHe7fQguu+25dA96gcryp9B+zk4x9DQbuwDGkpUt0H1PPOQrsDfG9nHRGwJXkgR3eAhy3o/8QWeh1Tl6JrpAPQfsY8gl278aYC2MqOiDo+/DxAuy9vYdyBrYdrgwJeRnJqM48J+GLQ1wR5iDgCuy6CrbvxRAHGNdASg0E7m+Mi//mkXEZg60CPh1v4uRe3DeUHY3oW9lZAY9rme8QGVcvbZf9owDzaAH7dWA/4FOADRPBubKDOAP8FtFGKeh/rkdEGgj5Cuw16f0PqIHoH6hmwYKtBTlJ2Af7GXSbj7K3B4PjHlBMhXb0YsYvvf97k5fpZH4B3YGOkD5Owdws+Jvp6qauPqet+8HtRJpOXcAv8XQMv52K6++5WQl5nf3dAhlAWwc8BXTLO/EVhnJg6n0J9H4YD88HSpWL89frBJ3M64xhwdAs6IgVaQH8ew5kxXBK+z3e8EQfyEny21aeoKHMBf0c9oVFGR9tmPrHsX/NJhH6epbjuSXUsRKK3rA7omysKfQ7KVLzInjvxpEa3ywD0OPjf1K/Q5hZ8IaA59SvY/CXw4N5VkP/oE8oh0Mus0iv7kSkL6Dmaos4ab5FO8PcN9PsWfNDIVC57RLdeVfic8Ss19UJWvAq+Kv0bUMewATiVw8+AicmcZWwmDKrY2OP5AvQ0+HzjENprHDP4/8mMjDkAua7TOB8r4YWeurkMrGiRphDXT9e3x69bhUU9Fj6njfL7p3l5Eh6wv1jHTANMlWN23XpdbC+ba+7qtfSZdw28RmxeN/Od+IDY52sl2JPPvG8C6iHeFkEfgZ3C/kQGYuRIfft9G6IOB53+jDYq+uwpPJ8kE70Kn8o+Ap/29AC1h/l9ul/U+lX56bXgYF/26n2Yu25DXQQzjTTZ1yPFOwz5fWsTf27lO/16vUA/1MXhvh4pxoY0A7vqW3yP9M8A3UfmDMZlxusB6mX1QI/g3AN8gKTyfuNY9uz/h8mChnmTF7mCi2V9R+ilDXqK9GVajqmR7qV8zbReUtioBvsBusTzD+s8gvkmumJ7Cx6x3IBDlrF0rQM49U0Bx9hNYE72gHO2US7PiKFRQXuF9PNQpwzEEG2wfbenh6Q9HUl4ADgKexnm5ohDf20ajod229Tk2NbVpYhz9IUbwVy0MpYgBnldgA5fzdAXooOVrezrJzY2wWfH8ohBg8nGMLy6aJPZ9bDvrMQUfzfKwzE9jbqEBtosjZ+A9k36z2SqNM70ZIOctOqFevmaHD+7rhwbpVxU7NLX4CS6btVD4PctzNhMG/Qa6rTCzi38cKbD/CxMomzdct+WFboJ/VGZBr1x3yT7VTue64BNOUdIvVK/ZXYAdfem0tcME4jJyb7vMYAxGM5SZDJ/frTIdBTgZ53bX/R7EpgfpICvrsHQMPd0wT5ltB819P9aafNbxdhdoH9Q85MyPdyplC9kfY5jyPqezVWxv/v+5a6cZLi+zRVym8/5Sz3Md4DX/Ux3oI9F6JQAhnJ9EgCvXPS/DnxQp6xnxbq4/razNXaDfY40qisa1CaCPvwK9e/4RFX7ADab8YGWgEXw+z73gcZcDGMJtwqDdAe5DrS1q1MfJsEjq1Dh7ZTjR4oC/YzcJfiw6CN0YF4BGO6GJs4JtV5sYj08zlNdf7rQIlwXzOa2yw/Yr2sFfD+mR8NcZHmtbBr0k2tMg/BW7Tvep+lFK31BTjqWoKXo64FNvRDTjacscG16PDJxfIClol1cK5NVWtJUfoLt78ad9dPO+wnzwwDraZxv38XQLyKfd3YH6AJ8Gl022DPanUha7wb0cu/T/JB3UubbVGkIOs0DXck2ryvcxTeSugJ+Ig9I++W43ayf67yftzDnQp0bDacU1mcQ3qg5b9Scl6E7ITxcjB9ABnD+l7RgiDXoy5fDUMjyaqCNVV5jp/MTMNR3/E/K12Lpjwdc77cHGqmjaZwKtbqdviDWiIwA/5FnNawxq3u0I+5CS7C8SvmcQhXytcI1kxvAzUhWHzVJEwdSRc6mix41BdzYMBe0dPnWYpLoBDkaKXRPekEcSrIm8lON1ST1ooZDi1mhDWNMfYPlK+tZyw8wRklSH1mDWvFT4L0auOyOLtrE7sgTwFIC7ccm37u3UucJGWPdY7oRbPFISTP/5YCffJLzG21m0vq92j+0kbahUbhXU9Hp7T535Mau4C2hLxUbmWEsX2vCtRPw27zAgblghj0OeQHl/E/24rF7za/ca43a0VkLyRoJ+ICRzfcyfwvtYmmrKngB/wjbb3i30dbs+TT3iGnwt/J1qZNszMrFPUEm3K0bpjXs47rirYP7XwauUbs+ysAB3QKRVUMN7cxQ0YY1jO34nKy/WAYrNn4UvY7uh3ZLmWvATFXe7nHNFv0OZ0HWHjsz1Hfc44NJ7/oJbfdBH2hE/3Oh0j6eL9a/FYx2X8me8zsdK9A07l1aFX+trkt6gYm+pSHGZD+a4VCn3NiMW1mTXn6QAl7RCI99UW0fzxfb1irevqGd/aHkqN1vOi5HYsr1vlaeRukfngU4dnWsg2uzcTc/pLy1+8xVfN5bNMwZDTO0iZyNhzK3Kmg0kjWWhfK3YENvgAeKTHGtvCz8AsTlJ9T1V5fH9RW1Gv3U2Ft8uU+1x4fC90C/81es66b/hOzyB2uNFZvZtZGuxdq3RXAB8+YFvya+CeIVvrtOG7+TGtYx7zGWCPCKa07eM+d+L8RTmtW44GyPM/0wljRZPNvhzA5PVV59Qr/9Te3v18nL39Tufp1c/W3t7TfA2g9lZ3NbGOJcPSn2R/c+r8zxcf1H5zEW8Ckbu8niPnFN3tmt2/NJ6/rkK81nJEXtcjCnuQW9OtXU5Gxzqz45zYrTQGYVvge6Yqwp6Rfbnda1rON25wXszSutm6hcOJHB7zYomlVpbfTKuvQV120zX0X9wWXsbz0/fjlZPMkH/PI15n1bFgYGs7onPNiSPerNc9fSf2ad9r3oeBBPk6294/7w2qRrtrxii10yl0Z9Cd/dN34H/lRD3Rj75lv7cUPf0J7vdHFOy++yRvnVtkp8cX81LPGe+4vfZ33yJfd4X0gflHapmH+c7ferydRX+H8vsu7wMEpZXDOkSR1Sy1zxpf3EF5S9k+YX32veWNnb/9kx+APZ68ym8nVbnZ9vObDTtc+bbLTgx+QMXPp97LPChTd4zuy76NiXjI/6Uejxxta1vys+fmAb/F1x8j1iwn4uPL3B9W1fhD5P5L/LvLiwi7s5cbaPLIQYCx0d7CHXP29d285jN+9xjxpj1vRN69pta+wqtJHb4srausAvLZBBXHcv9p4b5+pF3dDvkYJ1h2s8e1Cvk6qNv1Lfan+Nf/fdF8QQ80k5t837Wt+/L9awcxoTOmCMeUbnvO68vxW/qFIn9rfIB1Crb5TFBKyALvFeW6esF+/H4drlXLQ5piC3jbV4x3LNpag77+/OZ6vUOapjr1Iftb+3Un73xJxZehpbfE7XRmyxFX4dYEuq0LeOLX7Hqzq22Aqv9rGVf/cKMcV8w/5UZZwN8amVNbLVjvY1f3zVKD/1zw/2wW7aMFebNz0RI9vWf/WJ/qst/Vdb+q+29/9QZvjjuq81Plhf4Rga1xsPyu/0bA0f5dUNzfOYalxtVMbxEB+jQsP5pqVsEQPkeAdlc7o0yl2nwoN0t7dZymCu11rK5uuoTm0dNSubyVhjOaaY2x2WK3TJE30l/DAY1G+bqNbXir44oTzhV5O+saB/TjOdU9CBd0hLozL2TA6Kc8MifD5G3X1b0OC60ddp38s+4UxSQz+8pnXGlvP+xbm7pnNcrN16tpWSeZUq9HtxNvZp/xcwv6jQCnzO/O9c4bdinVz8g62hl35s2zldmdOmhU0pzr8dWedNTd0sMUHWu/K/F34kqbPuu3/7teH9+dduDa3tbCMna2P0fQu92Dvq23fE0Ax7uT9B+FLPg3IXkzr3zse8nTXM59CUvnxTNH21eKI6TVv014qX8rnRS8ks9OsKc1Vp3N54fgC8lnPKVn1O6CG9VXrsY+1EepTz57eOj2+oz+D98W3pr7+I3wC8oniMCd1fJ/z+NvPl1t5qfkgbbSVVfGGfbMVKoSYBbfnvTtv9dc0TsIb0UN8qPZ7vnxF6lHP9t46PV5K9pjmAQvH9F/bRkFca5seTD85Qv53955odbsnxpPLiJy18WV+N1BmEE3UvTupnmG/m9JDeKD32sXYqPV7UV/uB8fE6stfkA9OsMqXNl/XVQlKnOA3H4t96/knLn2AecJOvk+znqsvn/OXacs133u0HlHMVsMG7fZ0GvdnmD6hTGnxmvq5Lmta1qvXiPKayv9LgayUHGGrKk1HUp3E9FfC555fU1xnr+yDNc7R6H3N7fEhDSQ16evldK/YL/tRsetuazH3r/OaQT8WeQBOvju8X5O08I7dnYOl8YjPOMsvT3o2gDt/qjGNCZ2YcQt/uxfRILta83da8iGUOMcwLzCdZjiy+3DOY6Rfteobh7x0m2MsteRlJDOhwPYnacGMueqmt9fwZ6GGbuch4JIxjoyM+uFleykquuWKcmKeLtLefU68hT12I9WxJDmioxwY94g5u4EcOYHygS3q4b5EUtNmNr5rzc5fT14y0dd5Xb5aN7WV4UqN/lp+vqH+f5iT36K4twLSb5ecnOZgb9qKEPCfc3AN+YK4YtMU09dlgwwnm+B+wMLaxn2Gt9wDjC+H7rTsQoRx1kJPuiTo50NEbG/pF6rpbYg5+GMN4iXcRuFeJZ+L9HJjjTVd7ZZ7nIsci8NhIHW80L3OSBgZD3+oKjKt/4Ylp98Ie3BztjzoQfZOhfRjb2k7pO2zfVJrzw4LNAaxoKbTFfx6wmIN3O5lfbg5yZqKMVtp0F2Hoph7IhAx2/mK9y9nb3Y2lQ/Z1qAyvyFOuLZ8v2EsTvldr+Mrz7t2ZgA8r9Z6990PiPtrtxp3NdBeW7pQyW835V9AF3iP525+wP3mOoV1ewufmAN7Pd1nPpficXLiVnLKLx/VBrmCQpzwP1rItV2FjDlfw5YBWkdGRKTO3bWr+Gfh2W/BJQuAZR/RHv+Ij8pWy5BxCtjdZ0ljvblxDgvdBv3Uk9FkyfUT3KFeQojwf1MIyxC2JwYJx21SWF7FtfeAgX9Wr5nLM83miDolE/7PWW8G4I/DhckyW9VT3SZ+RYzzPxdg/qkPLPKh1PRquoV4Kc3CDTqIwx3mG1ZZcrEIlT/gU6kmdtpyqTZis92FX174e8QAvmF+/Kc8q+PIn5eQ+mlt5Lz9z0d/Yjlja7UO9Qg8xVfK8xcaUcjbsc1CPE1039vukHNFflL/aJfc/SMvm3PBlfty4IV93Dad4t5JJ8t/v/Inn5buX0Z7HNl+XHQcwNmNCct8O9DF2BLUx//pRfV3FbTSmyT0yAbEZMPYiBoHkD6XwrqBWP6xTvlv4u2VsQZt+A1u9MZXK+mo2jt9PzdsKdgJ4GyYjvKNEyOZrX2LvnA7el6Kl2b0IzbQ9mabNtm93BkfZxUeIRfwmydm4ITGwOBd3GuY7uby08a0Jm826at6ca/ckewm0cIXHUMV5to73h2EecbwTQgZfl92YxnBZt3W5HlUC8K0uwU9FH6scy37/wCd4pPCes4MYkvqdBVuXCakZ4y0L3jT7nmMfZVvsuGtL6yXitiEvdMFD8A3dzOcg6ylGg4ycshfW5OfVxybajblgyboTa7efFQzd1roFEfQLf3+4r0NodTfDu1v6bsdehIAr50ODDs3l2IztQZa/max9VH2Ywic6ZS/hLjmFzg1x95l/o9PtMffGtK1udg7+s29tD9aByc+M4cHuXUYu0/VRzibeKXzC/YLDnNfAp1PW2n4/hc5N5/6I7uRXrWf+JKX1TCmnqfxI1lyyRjcNtIGkiaykdl8AO/zPjh229RxlIGvAN16jcL+Gn8gq0o9npyHVysNZhPPTpDnXfKF3mHiFOVGfqXd6J+1PfaUcWAs6MTqXz5ODJ3RgdS30K7GGZy9Pwll1zTqTmaN7cV/Jz8xGn0Szag7mTLcfXVM/zXbUddLX6qKTx30qVr7/uKv7P6eM+4m5TOlneNe5j0PuDcPcyDu/OG6el5R49jGG+EkdkPmPLWdSqzHHme+Vz+UjvANR5jXQ+clDBeMe3mM47bN9Deg8JT7XRYPftnm6LYb2rSx2HNpia3tTs0q+8sb7C/K9ELx7oKLfKvvmrjtC2goYS37jmYsLnO89Xit5/PQTuczb5f9YDvP8e+KTHrO/m2O5s0k7CtbVktf/eBvlXhzS8ADnp9FHm4LNWDbY3hh5YJL7oRrPqzeeB3uuDcnOEQyf0gvl+rLeKuPZORCgNWULan72yI/tsJet6yi4HoFzxE12/iA/CwO0+A/mytntm7Ekx82QEzU8w4fzjMkcz5doWd5mckdn+V380jKBesLiemt7ECxh7rfbU1R930nxXrVehLg4CVdkj7ga9+KfnJNa14E+B3cwkTksmRNW8uGPbaZLWf2Gd3dztkaZqcvdaWPCeJ5a3Ey7zajQrvvgcmA3hA3ogeKsY5vcNM6p8F5mipx/S9mFTe484uL8fNvjrp1w3X43xNE24hZ9l/tzp9FHBblt0gOEB3n+/KZzKM1nkZ5r3/G8T/AKcozyifGqIdih17NH31r29vPQnmXuLHPPl7nynNwTcx2yjtmWf7t6lgzvYk5MJT8/RuPd0zKJE5fTtyN3R3Mqvuy9Jc2Yr8vNaVg/uLfmstUvPnZfTQvuG9dDTvQhRXJnY3P+qaNttOmr3A89jT4ayl2THBMeRLgHc92KU/Zr17bKGNpXsH85Vr1yfob3wsOcV6z6qdl6OJbTJIwLxLjnVr2Tt2PrfEzO52I7fC0eugO6YDlluslnxber8yJF4Le4B2UzTnQiNkbYF7USU3f9rPhrzczuaS7uP8Q4hSHBVb7+X9EZNN6tvWx6N7+jNT7PK/8e88ri3PYrr5l4RZ6cNySLQwVtfeCcbeLZJn6NTfSzvAVP+abZfEUWtE1+d9sV0GJuMxcfJosxtkGZqpnaDM1l8XTN64QzXQ4K3F1Pk2PyfiR/3xeslaorvDvIk0JcJ8I4P3LHceZPZ/7ogymoyRH/ezXTwzWUJbr8qbtY8311zjRYcqcliUEFWuV3oO9kLQDMZPdB7u7oZajoPD98U/PDp/YeUtOQaWdR3MnNfUm8UBm7nccsk7joPLaX6LJdnAvG6+R7FWkZ80Led5lujPterfcS5/PUY3c52zDfxDuo8YzFbJdTCeUifuIO+7XD9FID+mBl90+33VtfxISS2OT9+EtXH3dAjgKYl0IfVltLaT3jSOTNYPg8/j3b9wQa3TqLHu0K6nLYEH9k5DHXoyjJ6jeo9ed0F/90q3R/z2iq9Ybzw3MdDTG9XbujUU7avQMdurGZbgj+8XYUyRTYPdC54C8vnP17z5+LjyK+N6cJwUD+GZGzsv9ZXHmWJyfz33FNnrxP4kpAf7TGR9Vjqy4P4wIqMY2uTs9B1vJ41l37uzYP+FYrg/wDeQ1L/pMYqWpMG4n1zWxDe1zxIYbK879Ejk6Oay7KwXwB+Re7xO9rLZ/z1b3FMwLVMfyoMb/VPltEr/i0pXyTOOV7gtOBFotpSHxE0PMpvkN0v9Bj8/2jVt0CfnTcGKdSO8NRnP/IZabfLeSjjR4J+T6naYkDXDtInccsVyNH4vxulPYzTQ16b19WDuJp62Wc4nzGA85NPqWXj8OrJfi8PMa7frn+WZhAD9p3S90BekLIMGIwNPhLLvp6hBajA9kP6jGZEdq8jx/f//nu3S/f7vnnX+T5SH7/K//Xv/98TvFK2VMK/nPX4L/e4//f/1/ZbDnyf7w7/3n7f97VMfGvGggzSPz7z/8B6lZBTQ==';
>>>>>>> rilis-beta

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































































                                                                                                                                                                                                                     $________;
